# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

"""Reader for the constrained MP4/H.264 chunks generated by CVAT."""

from __future__ import annotations

import os
from collections.abc import Generator
from pathlib import Path

import PIL.Image

from .errors import UnsupportedVideoChunkError
from .models import DecoderInfo
from .utils import (
    OpenH264Decoder,
    iter_access_units_from_stream,
    read_video_track_from_stream,
    resolve_decoder_and_library,
    unload_library,
)

__all__ = ["DecoderInfo", "iter_frames", "resolve_decoder"]


def resolve_decoder(*, library_path: os.PathLike[str] | str | None = None) -> DecoderInfo:
    """Resolve an explicit, configured, or system OpenH264 library without downloading it."""

    info, library = resolve_decoder_and_library(library_path)
    unload_library(library)
    return info


def iter_frames(
    path: os.PathLike[str] | str,
    *,
    library_path: os.PathLike[str] | str | None = None,
) -> Generator[PIL.Image.Image, None, None]:
    """
    Decode a CVAT-generated constrained-baseline MP4 chunk sequentially.

    This adapter deliberately has no codec downloader or general-purpose media fallback.
    Per H.264, decoding an access unit always yields a decoded picture; combined with
    the one-access-unit-per-sample guarantee from ``iter_access_units_from_stream``,
    the decoder is expected to emit exactly ``len(track.samples)`` frames.
    """

    chunk_path = Path(path)

    file_size = chunk_path.stat().st_size
    file = chunk_path.open("rb")

    with file:
        track = read_video_track_from_stream(file, file_size)
        decoder_info, library = resolve_decoder_and_library(library_path)
        decoded_frame_count = 0

        try:
            # Construct inside the try so a decoder creation/initialization failure still
            # releases the library handle loaded for this chunk (no leaked loader reference).
            decoder = OpenH264Decoder(decoder_info, library=library)
            try:
                for access_unit in iter_access_units_from_stream(file, track):
                    image = decoder.decode(access_unit)
                    decoded_frame_count += 1
                    yield image
            finally:
                decoder.close()
        finally:
            unload_library(library)

    if decoded_frame_count != len(track.samples):
        raise UnsupportedVideoChunkError(
            f"Decoded {decoded_frame_count} frames from {len(track.samples)} AVC samples"
        )
