[program:rqscheduler]
command=/opt/cvat/wait_for_deps.sh
    python3 /opt/cvat/rqscheduler.py
        --host "%(ENV_CVAT_REDIS_INMEM_HOST)s"
        --port "%(ENV_CVAT_REDIS_INMEM_PORT)s"
        --password "%(ENV_CVAT_REDIS_INMEM_PASSWORD)s"
        -i 30
environment=VECTOR_EVENT_HANDLER="SynchronousLogstashHandler"
numprocs=1
autorestart=true
