# Generated by Django 3.2.16 on 2022-12-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitation',
            name='view_analytics',
        ),
        migrations.AlterField(
            model_name='limitation',
            name='lambda_requests',
            field=models.IntegerField(null=True),
        ),
    ]
