# Generated by Django 3.2.16 on 2022-12-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit_manager', '0002_auto_20221219_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='lambda_requests',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
