# Generated by Django 3.2.16 on 2022-12-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit_manager', '0003_alter_limitation_lambda_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='cloud_storages',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='lambda_requests',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='memberships',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='organizations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='projects',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='tasks',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='tasks_per_project',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='webhooks_per_organization',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='webhooks_per_project',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
