# Generated by Django 3.2.16 on 2022-12-28 11:22

import cvat.apps.limit_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit_manager', '0004_auto_20221222_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='type',
            field=models.CharField(choices=[('default', 'DEFAULT'), ('paid', 'PAID'), ('manually', 'MANUALLY')], default=cvat.apps.limit_manager.models.LimitationTypeChoice['DEFAULT'], max_length=32),
        ),
    ]
