# Generated by Django 2.1.9 on 2019-08-05 06:27

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion

def split_handlers(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    handler_model = apps.get_model('annotation', 'AnnotationHandler')
    dumper_model = apps.get_model('annotation', "AnnotationDumper")
    loader_model = apps.get_model('annotation', 'AnnotationLoader')


    for db_handler in handler_model.objects.all():
        if db_handler.type == "dumper":
            new_handler = dumper_model()
        else:
            new_handler = loader_model()

        new_handler.display_name = db_handler.display_name
        new_handler.format = db_handler.format
        new_handler.version = db_handler.version
        new_handler.handler = db_handler.handler
        new_handler.annotation_format = db_handler.annotation_format

        new_handler.save()
        db_handler.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationDumper',
            fields=[
                ('display_name', cvat.apps.engine.models.SafeCharField(max_length=256, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('handler', models.CharField(max_length=256)),
                ('annotation_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.AnnotationFormat')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AnnotationLoader',
            fields=[
                ('display_name', cvat.apps.engine.models.SafeCharField(max_length=256, primary_key=True, serialize=False)),
                ('format', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=16)),
                ('handler', models.CharField(max_length=256)),
                ('annotation_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.AnnotationFormat')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.RunPython(
            code=split_handlers,
        ),
        migrations.RemoveField(
            model_name='annotationhandler',
            name='annotation_format',
        ),
        migrations.DeleteModel(
            name='AnnotationHandler',
        ),
    ]
