# Generated by Django 4.2.25 on 2025-10-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import cvat.apps.engine.models


class Migration(migrations.Migration):

    replaces = [
        ("engine", "0001_release_v0_1_0"),
        (
            "engine",
            "0002_labeledpoints_labeledpointsattributeval_labeledpolygon_labeledpolygonattributeval_labeledpolyline_la",
        ),
        ("engine", "0003_objectpath_shapes"),
        ("engine", "0004_task_z_order"),
        ("engine", "0005_auto_20180609_1512"),
        ("engine", "0006_auto_20180629_1501"),
        ("engine", "0007_task_flipped"),
        ("engine", "0008_auto_20180917_1424"),
        ("engine", "0009_auto_20180917_1424"),
        ("engine", "0010_auto_20181011_1517"),
        ("engine", "0011_add_task_source_and_safecharfield"),
        ("engine", "0012_auto_20181025_1618"),
        ("engine", "0013_auth_no_default_permissions"),
        ("engine", "0014_job_max_shape_id"),
        ("engine", "0015_db_redesign_20190217"),
        ("engine", "0016_attribute_spec_20190217"),
        ("engine", "0017_db_redesign_20190221"),
        ("engine", "0018_jobcommit"),
        ("engine", "0019_frame_selection"),
        ("engine", "0020_remove_task_flipped"),
        ("engine", "0021_auto_20190826_1827"),
        ("engine", "0022_auto_20191004_0817"),
        ("engine", "0023_auto_20200113_1323"),
        ("engine", "0024_auto_20191023_1025"),
        ("engine", "0025_auto_20200324_1222"),
        ("engine", "0026_auto_20200719_1511"),
        ("engine", "0027_auto_20200719_1552"),
        ("engine", "0028_labelcolor"),
        ("engine", "0029_data_storage_method"),
        ("engine", "0030_auto_20200914_1331"),
        ("engine", "0031_auto_20201011_0220"),
        ("engine", "0032_remove_task_z_order"),
        ("engine", "0033_projects_adjastment"),  # spellchecker:disable-line
        ("engine", "0034_auto_20201125_1426"),
        ("engine", "0035_data_storage"),
        ("engine", "0036_auto_20201216_0943"),
        ("engine", "0037_task_subset"),
        ("engine", "0038_manifest"),
        ("engine", "0039_auto_training"),
        ("engine", "0040_cloud_storage"),
        ("engine", "0041_auto_20210827_0258"),
        ("engine", "0042_auto_20210830_1056"),
        ("engine", "0043_auto_20211027_0718"),
        ("engine", "0044_auto_20211115_0858"),
        ("engine", "0045_auto_20211123_0824"),
        ("engine", "0046_data_sorting_method"),
        ("engine", "0047_auto_20211110_1938"),
        ("engine", "0048_auto_20211112_1918"),
        ("engine", "0049_auto_20220202_0710"),
        ("engine", "0050_auto_20220211_1425"),
        ("engine", "0051_auto_20220220_1824"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", cvat.apps.engine.models.SafeCharField(max_length=256)),
                ("size", models.PositiveIntegerField()),
                ("mode", models.CharField(max_length=32)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("annotation", "ANNOTATION"),
                            ("validation", "VALIDATION"),
                            ("completed", "COMPLETED"),
                        ],
                        default="annotation",
                        max_length=32,
                    ),
                ),
                ("bug_tracker", models.CharField(blank=True, default="", max_length=2000)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("overlap", models.PositiveIntegerField(null=True)),
                ("z_order", models.BooleanField(default=False)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("segment_size", models.PositiveIntegerField(default=0)),
                ("image_quality", models.PositiveSmallIntegerField(default=50)),
                ("frame_filter", models.CharField(blank=True, default="", max_length=256)),
                ("start_frame", models.PositiveIntegerField(default=0)),
                ("stop_frame", models.PositiveIntegerField(default=0)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_frame", models.IntegerField()),
                ("stop_frame", models.IntegerField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.task"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", cvat.apps.engine.models.SafeCharField(max_length=64)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.task"
                    ),
                ),
                ("color", models.CharField(default="", max_length=8)),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("task", "name")},
            },
        ),
        migrations.CreateModel(
            name="AttributeSpec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.label"
                    ),
                ),
                ("default_value", models.CharField(max_length=128)),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("checkbox", "CHECKBOX"),
                            ("radio", "RADIO"),
                            ("number", "NUMBER"),
                            ("text", "TEXT"),
                            ("select", "SELECT"),
                        ],
                        max_length=16,
                    ),
                ),
                ("mutable", models.BooleanField()),
                ("name", models.CharField(max_length=64)),
                ("values", models.CharField(max_length=4096)),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("label", "name")},
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.segment"
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("annotation", "ANNOTATION"),
                            ("validation", "VALIDATION"),
                            ("completed", "COMPLETED"),
                        ],
                        default="annotation",
                        max_length=32,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("annotation", "ANNOTATION"),
                            ("validation", "VALIDATION"),
                            ("acceptance", "ACCEPTANCE"),
                        ],
                        default=cvat.apps.engine.models.StageChoice["ANNOTATION"],
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("in progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                            ("rejected", "REJECTED"),
                        ],
                        default=cvat.apps.engine.models.StateChoice["NEW"],
                        max_length=32,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LabeledImage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("frame", models.PositiveIntegerField()),
                ("group", models.PositiveIntegerField(null=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="engine.job"),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.label"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "AUTO"), ("manual", "MANUAL")],
                        default="manual",
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LabeledShape",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("frame", models.PositiveIntegerField()),
                ("group", models.PositiveIntegerField(null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rectangle", "RECTANGLE"),
                            ("polygon", "POLYGON"),
                            ("polyline", "POLYLINE"),
                            ("points", "POINTS"),
                            ("ellipse", "ELLIPSE"),
                            ("cuboid", "CUBOID"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occluded", models.BooleanField(default=False)),
                ("z_order", models.IntegerField(default=0)),
                ("points", cvat.apps.engine.models.FloatArrayField(default="")),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="engine.job"),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.label"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "AUTO"), ("manual", "MANUAL")],
                        default="manual",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("rotation", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LabeledTrack",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("frame", models.PositiveIntegerField()),
                ("group", models.PositiveIntegerField(null=True)),
                (
                    "job",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="engine.job"),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.label"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("auto", "AUTO"), ("manual", "MANUAL")],
                        default="manual",
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TrackedShape",
            fields=[
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rectangle", "RECTANGLE"),
                            ("polygon", "POLYGON"),
                            ("polyline", "POLYLINE"),
                            ("points", "POINTS"),
                            ("ellipse", "ELLIPSE"),
                            ("cuboid", "CUBOID"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occluded", models.BooleanField(default=False)),
                ("z_order", models.IntegerField(default=0)),
                ("points", cvat.apps.engine.models.FloatArrayField(default="")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("frame", models.PositiveIntegerField()),
                ("outside", models.BooleanField(default=False)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.labeledtrack"
                    ),
                ),
                ("rotation", models.FloatField(default=0)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", cvat.apps.engine.models.SafeCharField(max_length=256)),
                ("bug_tracker", models.CharField(blank=True, default="", max_length=2000)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("annotation", "ANNOTATION"),
                            ("validation", "VALIDATION"),
                            ("completed", "COMPLETED"),
                        ],
                        default="annotation",
                        max_length=32,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                related_query_name="task",
                to="engine.project",
            ),
        ),
        migrations.CreateModel(
            name="TrackedShapeAttributeVal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", cvat.apps.engine.models.SafeCharField(max_length=4096)),
                (
                    "shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.trackedshape"
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.attributespec"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chunk_size", models.PositiveIntegerField(null=True)),
                ("size", models.PositiveIntegerField(default=0)),
                ("image_quality", models.PositiveSmallIntegerField(default=50)),
                ("start_frame", models.PositiveIntegerField(default=0)),
                ("stop_frame", models.PositiveIntegerField(default=0)),
                ("frame_filter", models.CharField(blank=True, default="", max_length=256)),
                (
                    "compressed_chunk_type",
                    models.CharField(
                        choices=[("video", "VIDEO"), ("imageset", "IMAGESET"), ("list", "LIST")],
                        default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                        max_length=32,
                    ),
                ),
                (
                    "original_chunk_type",
                    models.CharField(
                        choices=[("video", "VIDEO"), ("imageset", "IMAGESET"), ("list", "LIST")],
                        default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                        max_length=32,
                    ),
                ),
                (
                    "storage_method",
                    models.CharField(
                        choices=[("cache", "CACHE"), ("file_system", "FILE_SYSTEM")],
                        default=cvat.apps.engine.models.StorageMethodChoice["FILE_SYSTEM"],
                        max_length=15,
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[
                            ("cloud_storage", "CLOUD_STORAGE"),
                            ("local", "LOCAL"),
                            ("share", "SHARE"),
                        ],
                        default=cvat.apps.engine.models.StorageChoice["LOCAL"],
                        max_length=15,
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="engine.data",
            ),
        ),
        migrations.CreateModel(
            name="RemoteFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.CharField(max_length=1024)),
                (
                    "data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_files",
                        to="engine.data",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ServerFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.CharField(max_length=1024)),
                (
                    "data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="server_files",
                        to="engine.data",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="frame_filter",
        ),
        migrations.RemoveField(
            model_name="task",
            name="image_quality",
        ),
        migrations.RemoveField(
            model_name="task",
            name="size",
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_frame",
        ),
        migrations.RemoveField(
            model_name="task",
            name="stop_frame",
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(default="", max_length=1024)),
                ("frame", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                (
                    "data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="engine.data",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(default="", max_length=1024)),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                (
                    "data",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video",
                        to="engine.data",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ClientFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=1024,
                        storage=cvat.apps.engine.models.MyFileSystemStorage(),
                        upload_to=cvat.apps.engine.models.upload_path_handler,
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_files",
                        to="engine.data",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("data", "file")},
            },
        ),
        migrations.CreateModel(
            name="JobCommit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="engine.job",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("scope", models.CharField(default="", max_length=32)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LabeledImageAttributeVal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", cvat.apps.engine.models.SafeCharField(max_length=4096)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.attributespec"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.labeledimage"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="task",
            name="z_order",
        ),
        migrations.AddField(
            model_name="label",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="engine.project",
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="task",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="engine.task"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating", models.FloatField(default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("frame", models.PositiveIntegerField()),
                ("position", cvat.apps.engine.models.FloatArrayField(default="")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="engine.job",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LabeledShapeAttributeVal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", cvat.apps.engine.models.SafeCharField(max_length=4096)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.attributespec"
                    ),
                ),
                (
                    "shape",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.labeledshape"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="task",
            name="dimension",
            field=models.CharField(
                choices=[("3d", "DIM_3D"), ("2d", "DIM_2D")],
                default=cvat.apps.engine.models.DimensionType["DIM_2D"],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="RelatedFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "path",
                    models.FileField(
                        max_length=1024,
                        storage=cvat.apps.engine.models.MyFileSystemStorage(),
                        upload_to=cvat.apps.engine.models.upload_path_handler,
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_files",
                        to="engine.data",
                    ),
                ),
                (
                    "primary_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_files",
                        to="engine.image",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("data", "path")},
            },
        ),
        migrations.AddField(
            model_name="task",
            name="subset",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="LabeledTrackAttributeVal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", cvat.apps.engine.models.SafeCharField(max_length=4096)),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.attributespec"
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.labeledtrack"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CloudStorage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("AWS_S3_BUCKET", "AWS_S3"),
                            ("AZURE_CONTAINER", "AZURE_CONTAINER"),
                            ("GOOGLE_DRIVE", "GOOGLE_DRIVE"),
                            ("GOOGLE_CLOUD_STORAGE", "GOOGLE_CLOUD_STORAGE"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource", models.CharField(max_length=222)),
                ("display_name", models.CharField(max_length=63)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("credentials", models.CharField(max_length=500)),
                (
                    "credentials_type",
                    models.CharField(
                        choices=[
                            ("KEY_SECRET_KEY_PAIR", "KEY_SECRET_KEY_PAIR"),
                            ("ACCOUNT_NAME_TOKEN_PAIR", "ACCOUNT_NAME_TOKEN_PAIR"),
                            ("KEY_FILE_PATH", "KEY_FILE_PATH"),
                            ("ANONYMOUS_ACCESS", "ANONYMOUS_ACCESS"),
                        ],
                        max_length=29,
                    ),
                ),
                ("specific_attributes", models.CharField(blank=True, max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloud_storages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cloudstorages",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("provider_type", "resource", "credentials")},
            },
        ),
        migrations.AddField(
            model_name="data",
            name="cloud_storage",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data",
                to="engine.cloudstorage",
            ),
        ),
        migrations.CreateModel(
            name="Manifest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(default="manifest.jsonl", max_length=1024)),
                (
                    "cloud_storage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifests",
                        to="engine.cloudstorage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="data",
            name="sorting_method",
            field=models.CharField(
                choices=[
                    ("lexicographical", "LEXICOGRAPHICAL"),
                    ("natural", "NATURAL"),
                    ("predefined", "PREDEFINED"),
                    ("random", "RANDOM"),
                ],
                default=cvat.apps.engine.models.SortingMethod["LEXICOGRAPHICAL"],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("message", models.TextField(default="")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="engine.issue",
                    ),
                ),
            ],
        ),
    ]
