
# Copyright (C) 2018-2022 Intel Corporation
#
# SPDX-License-Identifier: MIT

# Generated by Django 2.0.3 on 2018-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20180629_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flipped',
            field=models.BooleanField(default=False),
        ),
    ]
