# Generated by Django 2.0.3 on 2018-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_auto_20180917_1424'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE "engine_objectpath" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_objectpathattributeval" ALTER COLUMN "track_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedbox" ALTER COLUMN "track_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpoints" ALTER COLUMN "track_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolygon" ALTER COLUMN "track_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolyline" ALTER COLUMN "track_id" TYPE bigint;'),

        migrations.RunSQL('ALTER TABLE "engine_trackedbox" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpoints" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolygon" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolyline" ALTER COLUMN "id" TYPE bigint;'),

        migrations.RunSQL('ALTER TABLE "engine_trackedboxattributeval" ALTER COLUMN "box_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpointsattributeval" ALTER COLUMN "points_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolygonattributeval" ALTER COLUMN "polygon_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolylineattributeval" ALTER COLUMN "polyline_id" TYPE bigint;'),

        migrations.RunSQL('ALTER TABLE "engine_trackedboxattributeval" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpointsattributeval" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolygonattributeval" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_trackedpolylineattributeval" ALTER COLUMN "id" TYPE bigint;'),

        migrations.RunSQL('ALTER TABLE "engine_labeledbox" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpoints" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpolygon" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpolyline" ALTER COLUMN "id" TYPE bigint;'),

        migrations.RunSQL('ALTER TABLE "engine_labeledboxattributeval" ALTER COLUMN "box_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpointsattributeval" ALTER COLUMN "points_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpolygonattributeval" ALTER COLUMN "polygon_id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpolylineattributeval" ALTER COLUMN "polyline_id" TYPE bigint;'),

        migrations.RunSQL('ALTER TABLE "engine_labeledboxattributeval" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpointsattributeval" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpolygonattributeval" ALTER COLUMN "id" TYPE bigint;'),
        migrations.RunSQL('ALTER TABLE "engine_labeledpolylineattributeval" ALTER COLUMN "id" TYPE bigint;'),
    ]
