# Generated by Django 2.1.5 on 2019-02-21 12:25

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


def copy_annotations_forward(apps, schema_editor):
    pass

def copy_annotations_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0015_rest_api_20190217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame', models.PositiveIntegerField()),
                ('group_id', models.PositiveIntegerField(default=0)),
                ('client_id', models.BigIntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='LabeledImageAttributeVal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', cvat.apps.engine.models.SafeCharField(max_length=64)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LabeledShapeAttributeVal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', cvat.apps.engine.models.SafeCharField(max_length=64)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LabeledTrackAttributeVal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', cvat.apps.engine.models.SafeCharField(max_length=64)),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TrackedShape',
            fields=[
                ('type', models.CharField(choices=[('RECTANGLE', 'rectangle'), ('POLYGON', 'polygon'), ('POLYLINE', 'polyline'), ('POINTS', 'points')], max_length=16)),
                ('occluded', models.BooleanField(default=False)),
                ('z_order', models.IntegerField(default=0)),
                ('points', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame', models.PositiveIntegerField()),
                ('outside', models.BooleanField(default=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TrackedShapeAttributeVal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', cvat.apps.engine.models.SafeCharField(max_length=64)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.TrackedShape')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.AttributeSpec')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LabeledImage',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Annotation')),
            ],
            bases=('engine.annotation',),
        ),
        migrations.CreateModel(
            name='LabeledShape',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Annotation')),
                ('type', models.CharField(choices=[('RECTANGLE', 'rectangle'), ('POLYGON', 'polygon'), ('POLYLINE', 'polyline'), ('POINTS', 'points')], max_length=16)),
                ('occluded', models.BooleanField(default=False)),
                ('z_order', models.IntegerField(default=0)),
                ('points', models.TextField()),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
            bases=('engine.annotation', models.Model),
        ),
        migrations.CreateModel(
            name='LabeledTrack',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='engine.Annotation')),
            ],
            bases=('engine.annotation',),
        ),
        migrations.AddField(
            model_name='annotation',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Job'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Label'),
        ),
        migrations.AddField(
            model_name='trackedshape',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabeledTrack'),
        ),
        migrations.AddField(
            model_name='labeledtrackattributeval',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabeledTrack'),
        ),
        migrations.AddField(
            model_name='labeledshapeattributeval',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabeledShape'),
        ),
        migrations.AddField(
            model_name='labeledimageattributeval',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.LabeledImage'),
        ),


        migrations.RunPython(
            code=copy_annotations_forward,
            reverse_code=copy_annotations_backward,
        ),


        migrations.RemoveField(
            model_name='labeledbox',
            name='job',
        ),
        migrations.RemoveField(
            model_name='labeledbox',
            name='label',
        ),
        migrations.RemoveField(
            model_name='labeledboxattributeval',
            name='box',
        ),
        migrations.RemoveField(
            model_name='labeledboxattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='labeledpoints',
            name='job',
        ),
        migrations.RemoveField(
            model_name='labeledpoints',
            name='label',
        ),
        migrations.RemoveField(
            model_name='labeledpointsattributeval',
            name='points',
        ),
        migrations.RemoveField(
            model_name='labeledpointsattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='labeledpolygon',
            name='job',
        ),
        migrations.RemoveField(
            model_name='labeledpolygon',
            name='label',
        ),
        migrations.RemoveField(
            model_name='labeledpolygonattributeval',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='labeledpolygonattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='labeledpolyline',
            name='job',
        ),
        migrations.RemoveField(
            model_name='labeledpolyline',
            name='label',
        ),
        migrations.RemoveField(
            model_name='labeledpolylineattributeval',
            name='polyline',
        ),
        migrations.RemoveField(
            model_name='labeledpolylineattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='objectpath',
            name='job',
        ),
        migrations.RemoveField(
            model_name='objectpath',
            name='label',
        ),
        migrations.RemoveField(
            model_name='objectpathattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='objectpathattributeval',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackedbox',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackedboxattributeval',
            name='box',
        ),
        migrations.RemoveField(
            model_name='trackedboxattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='trackedpoints',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackedpointsattributeval',
            name='points',
        ),
        migrations.RemoveField(
            model_name='trackedpointsattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='trackedpolygon',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackedpolygonattributeval',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='trackedpolygonattributeval',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='trackedpolyline',
            name='track',
        ),
        migrations.RemoveField(
            model_name='trackedpolylineattributeval',
            name='polyline',
        ),
        migrations.RemoveField(
            model_name='trackedpolylineattributeval',
            name='spec',
        ),
        migrations.DeleteModel(
            name='LabeledBox',
        ),
        migrations.DeleteModel(
            name='LabeledBoxAttributeVal',
        ),
        migrations.DeleteModel(
            name='LabeledPoints',
        ),
        migrations.DeleteModel(
            name='LabeledPointsAttributeVal',
        ),
        migrations.DeleteModel(
            name='LabeledPolygon',
        ),
        migrations.DeleteModel(
            name='LabeledPolygonAttributeVal',
        ),
        migrations.DeleteModel(
            name='LabeledPolyline',
        ),
        migrations.DeleteModel(
            name='LabeledPolylineAttributeVal',
        ),
        migrations.DeleteModel(
            name='ObjectPath',
        ),
        migrations.DeleteModel(
            name='ObjectPathAttributeVal',
        ),
        migrations.DeleteModel(
            name='TrackedBox',
        ),
        migrations.DeleteModel(
            name='TrackedBoxAttributeVal',
        ),
        migrations.DeleteModel(
            name='TrackedPoints',
        ),
        migrations.DeleteModel(
            name='TrackedPointsAttributeVal',
        ),
        migrations.DeleteModel(
            name='TrackedPolygon',
        ),
        migrations.DeleteModel(
            name='TrackedPolygonAttributeVal',
        ),
        migrations.DeleteModel(
            name='TrackedPolyline',
        ),
        migrations.DeleteModel(
            name='TrackedPolylineAttributeVal',
        ),
    ]
