# Generated by Django 2.1.7 on 2019-03-28 05:03

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0016_auto_20190221_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='file',
            field=models.FileField(max_length=1024, storage=cvat.apps.engine.models.MyFileSystemStorage(), upload_to=cvat.apps.engine.models.upload_path_handler),
        ),
    ]
