# Generated by Django 2.1.7 on 2019-04-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0018_remove_job_max_shape_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='overlap',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
