# Generated by Django 2.2.4 on 2019-08-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20190826_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_chunk_size',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
