# Generated by Django 2.2.8 on 2020-01-13 13:23

from django.db import migrations

import cvat.apps.engine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0022_auto_20191004_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledimageattributeval',
            name='value',
            field=cvat.apps.engine.models.SafeCharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='labeledshapeattributeval',
            name='value',
            field=cvat.apps.engine.models.SafeCharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='labeledtrackattributeval',
            name='value',
            field=cvat.apps.engine.models.SafeCharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='trackedshapeattributeval',
            name='value',
            field=cvat.apps.engine.models.SafeCharField(max_length=4096),
        ),
    ]
