# Generated by Django 2.2.10 on 2020-04-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0024_auto_20200225_0657_squashed_0029_auto_20200309_0733'),
        ('engine', '0025_auto_20200324_1222'),
    ]

    operations = [
    ]
