# Generated by Django 2.2.10 on 2020-03-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        ('engine', '0025_auto_20200324_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledshape',
            name='annotation_type',
            field=models.CharField(choices=[('Auto', 'AUTO'), ('Manual', 'MANUAL')], default='Manual', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='labeledshape',
            name='type',
            field=models.CharField(choices=[('rectangle', 'RECTANGLE'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('points', 'POINTS'), ('cuboid', 'CUBOID')], max_length=16),
        ),
        migrations.AlterField(
            model_name='trackedshape',
            name='type',
            field=models.CharField(choices=[('rectangle', 'RECTANGLE'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('points', 'POINTS'), ('cuboid', 'CUBOID')], max_length=16),
        ),
        migrations.AddField(
            model_name='labeledimage',
            name='annotation_type',
            field=models.CharField(choices=[('Auto', 'AUTO'), ('Manual', 'MANUAL')], default='Manual', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='labeledtrack',
            name='annotation_type',
            field=models.CharField(choices=[('Auto', 'AUTO'), ('Manual', 'MANUAL')], default='Manual', max_length=16, null=True),
        ),
    ]
