# Generated by Django 2.2.13 on 2020-07-10 13:52

from django.db import migrations, models
from cvat.apps.dataset_manager.formats.utils import get_color_from_label_name, rgb2hex

def alter_label_colors(apps, schema_editor):
    Label = apps.get_model('engine', 'Label')
    Task = apps.get_model('engine', 'Task')

    for task in Task.objects.all():
        for label_id, label in enumerate(Label.objects.filter(task_id=task.id)):
            label.color = rgb2hex(get_color_from_label_name(label.name, label_id))
            label.save()

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0025_auto_20200324_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.RunPython(
            code=alter_label_colors,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
