# Generated by Django 2.2.13 on 2020-08-11 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_auto_20200719_1552'),
        ('engine', '0026_labelcolor'),
    ]

    operations = [
    ]
