# Generated by Django 2.2.13 on 2020-07-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_auto_20200719_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pluginoption',
            name='plugin',
        ),
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.DeleteModel(
            name='PluginOption',
        ),
    ]
