# Generated by Django 2.2.13 on 2020-08-13 05:49

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0027_auto_20200719_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='storage_method',
            field=models.CharField(choices=[('cache', 'CACHE'), ('file_system', 'FILE_SYSTEM')], default=cvat.apps.engine.models.StorageMethodChoice('file_system'), max_length=15),
        ),
    ]
