# Generated by Django 3.1.1 on 2020-10-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_auto_20200914_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
