# Generated by Django 3.1.1 on 2020-09-24 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0030_auto_20200914_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignee',
        ),
        migrations.AddField(
            model_name='label',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.project'),
        ),
        migrations.AlterField(
            model_name='label',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.task'),
        ),
    ]
