# Generated by Django 3.1.1 on 2020-10-22 09:29

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0032_remove_task_z_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='uploaded_data_storage_location',
            field=models.CharField(
                choices=[('local', 'LOCAL'), ('share', 'SHARE')],
                default=cvat.apps.engine.models.UploadedDataStorageLocationChoice['LOCAL'],
                max_length=15
            ),
        ),
    ]
