# Generated by Django 3.1.1 on 2020-12-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0032_remove_task_z_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskToMerge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=20)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to_merge', to='engine.data')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
