# Generated by Django 3.1.1 on 2021-02-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0038_auto_20210211_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingproject',
            name='cvat_project',
        ),
        migrations.AddField(
            model_name='project',
            name='training_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.trainingproject'),
        ),
    ]
