# Generated by Django 3.1.1 on 2020-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0039_clowderfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clowderfile',
            old_name='file',
            new_name='clowderid',
        ),
        migrations.AddField(
            model_name='clowderfile',
            name='name',
            field=models.CharField(default='bla.jpg', max_length=2048),
            preserve_default=False,
        ),
    ]
