# Generated by Django 3.1.10 on 2021-06-15 13:45

from django.db import migrations, models

def set_to_null(apps, schema_editor):
    model_list = ["labeledimage", "labeledshape", "labeledtrack"]
    for model_name in model_list:
        Annotation = apps.get_model("engine", model_name)
        Annotation.objects.update(date_modified=None)

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0040_cloud_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledimage',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labeledshape',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labeledtrack',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.RunPython(set_to_null),
    ]
