# Generated by Django 3.1.10 on 2021-07-09 08:39

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0040_cloud_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstorage',
            name='credentials_type',
            field=models.CharField(choices=[('TEMP_KEY_SECRET_KEY_TOKEN_SET', 'TEMP_KEY_SECRET_KEY_TOKEN_SET'), ('KEY_SECRET_KEY_PAIR', 'KEY_SECRET_KEY_PAIR'), ('ACCOUNT_NAME_TOKEN_PAIR', 'ACCOUNT_NAME_TOKEN_PAIR'), ('ANONYMOUS_ACCESS', 'ANONYMOUS_ACCESS')], max_length=29),
        ),
    ]
