# Generated by Django 3.1.1 on 2021-01-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0041_clowderfile_srcdatasetid'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='clowder_api_key',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
    ]
