# Generated by Django 3.1.13 on 2021-10-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0042_auto_20210830_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
