# Generated by Django 3.1.13 on 2021-10-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0042_auto_20210830_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledshape',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackedshape',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
