# Generated by Django 3.2.8 on 2021-11-02 20:50

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_auto_20211026_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='job',
            name='stage',
            field=models.CharField(choices=[('annotation', 'ANNOTATION'), ('validation', 'VALIDATION'), ('acceptance', 'ACCEPTANCE')], default=cvat.apps.engine.models.StageChoice['ANNOTATION'], max_length=32),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(choices=[('new', 'NEW'), ('in progress', 'IN_PROGRESS'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED')], default=cvat.apps.engine.models.StateChoice['NEW'], max_length=32),
        ),
    ]
