# Generated by Django 3.1.13 on 2021-11-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_auto_20211027_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeledshape',
            name='rotation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trackedshape',
            name='rotation',
            field=models.FloatField(default=0),
        ),
    ]
