# Generated by Django 3.1.13 on 2021-11-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_auto_20211027_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstorage',
            name='credentials_type',
            field=models.CharField(choices=[('KEY_SECRET_KEY_PAIR', 'KEY_SECRET_KEY_PAIR'), ('ACCOUNT_NAME_TOKEN_PAIR', 'ACCOUNT_NAME_TOKEN_PAIR'), ('KEY_FILE_PATH', 'KEY_FILE_PATH'), ('API_KEY', 'API_KEY'), ('ANONYMOUS_ACCESS', 'ANONYMOUS_ACCESS')], max_length=29),
        ),
    ]
