# Generated by Django 3.2.8 on 2021-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0043_auto_20211027_0718'),
        ('engine', '0044_auto_20211102_2050'),
    ]

    operations = [
    ]
