# Generated by Django 3.2.8 on 2021-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0045_merge_0043_auto_20211027_0718_0044_auto_20211102_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
