# Generated by Django 3.2.12 on 2022-02-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0049_auto_20220202_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprojectimage',
            name='task',
        ),
        migrations.RemoveField(
            model_name='trainingprojectlabel',
            name='cvat_label',
        ),
        migrations.RemoveField(
            model_name='project',
            name='training_project',
        ),
        migrations.DeleteModel(
            name='TrainingProject',
        ),
        migrations.DeleteModel(
            name='TrainingProjectImage',
        ),
        migrations.DeleteModel(
            name='TrainingProjectLabel',
        ),
    ]
