# Generated by Django 3.2.12 on 2022-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0050_auto_20220211_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstorage',
            name='specific_attributes',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
