# Generated by Django 3.2.12 on 2022-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_auto_20220220_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='orientation',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
