# Generated by Django 3.2.12 on 2022-04-12 18:45

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_auto_20220220_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='file',
            field=models.FileField(max_length=1024, upload_to=cvat.apps.engine.models.client_file_upload_path_handler),
        ),
        migrations.AlterField(
            model_name='relatedfile',
            name='path',
            field=models.FileField(max_length=1024, upload_to=cvat.apps.engine.models.related_file_upload_path_handler),
        ),
    ]
