# Generated by Django 3.2.12 on 2022-06-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0052_alter_cloudstorage_specific_attributes'),
        ('engine', '0052_auto_20220412_1845'),
    ]

    operations = [
    ]
