# Generated by Django 3.1.1 on 2020-12-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0052_alter_cloudstorage_specific_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.FloatField(default=25),
        ),
    ]
