# Generated by Django 3.2.12 on 2022-06-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0053_data_deleted_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='edges',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='elements',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='sublabels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.label'),
        ),
        migrations.AddField(
            model_name='label',
            name='template',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('bbox', 'BBOX'), ('ellipse', 'ELLIPSE'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('points', 'POINTS'), ('cuboid', 'CUBOID'), ('cuboid_3d', 'CUBOID_3D'), ('skeleton', 'SKELETON'), ('tag', 'TAG')], default=None, max_length=32, null=True),
        ),
    ]
