# Generated by Django 3.2.12 on 2022-06-23 05:49

import cvat.apps.engine.models
import cvat.rebotics.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0054_auto_20220620_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='S3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1024, storage=cvat.rebotics.storage.CustomAWSMediaStorage, upload_to=cvat.apps.engine.models.s3_upload_path_handler)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s3_files', to='engine.data')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('data', 'file')},
            },
        ),
    ]
