# Generated by Django 3.2.12 on 2022-06-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0054_auto_20220621_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='template',
            new_name='svg',
        ),
    ]
