# Generated by Django 3.2.12 on 2022-06-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0055_rename_template_label_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='sublabels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_label', to='engine.label'),
        ),
    ]
