# Generated by Django 3.2.12 on 2022-06-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0056_alter_label_sublabels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='sublabels',
        ),
        migrations.AddField(
            model_name='label',
            name='parent_label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sublabels', to='engine.label'),
        ),
    ]
