# Generated by Django 3.2.14 on 2022-07-19 12:14

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0057_alter_label_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='type',
            field=models.CharField(choices=[('bbox', 'BBOX'), ('ellipse', 'ELLIPSE'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('points', 'POINTS'), ('cuboid', 'CUBOID'), ('cuboid_3d', 'CUBOID_3D'), ('skeleton', 'SKELETON'), ('tag', 'TAG'), ('any', 'ANY')], default=cvat.apps.engine.models.LabelType['ANY'], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='skeleton',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engine.label'),
        ),
    ]
