# Generated by Django 3.2.14 on 2022-07-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0056_jobs_previews'),
        ('engine', '0058_auto_20220719_1214'),
    ]

    operations = [
    ]
