# Generated by Django 3.2.13 on 2022-06-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0059_auto_20220630_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedskeleton',
            name='frame',
        ),
    ]
