# Generated by Django 3.2.14 on 2022-07-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0059_merge_0056_jobs_previews_0058_auto_20220719_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skeleton',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='skeleton',
            name='elements',
        ),
    ]
