# Generated by Django 3.2.12 on 2022-03-14 10:51
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0060_alter_label_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.task')),
                ('key', models.CharField(default='', max_length=4096)),
                ('value', models.CharField(default='', max_length=4096)),
            ],
        ),
    ]
