# Generated by Django 3.2.13 on 2022-06-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0060_remove_trackedskeleton_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='edges',
        ),
        migrations.RemoveField(
            model_name='label',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='label',
            name='svg',
        ),
        migrations.CreateModel(
            name='Skeleton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField(default=None, null=True)),
                ('elements', models.JSONField(null=True)),
                ('edges', models.JSONField(null=True)),
                ('root', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.label')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('root',)},
            },
        ),
    ]
