# Generated by Django 3.2.15 on 2022-10-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0055_s3file'),
        ('engine', '0060_alter_label_parent'),
    ]

    operations = [
    ]
