# Generated by Django 3.2.15 on 2022-10-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0061_merge_0055_s3file_0060_alter_label_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skeleton',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
