# Generated by Django 3.2.16 on 2023-01-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0062_delete_previews'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='custom_segments',
            field=models.BooleanField(default=False),
        ),
    ]
