# Generated by Django 3.2.17 on 2023-02-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0062_delete_previews'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('task', 'project', 'name', 'parent')},
        ),
    ]
