# Generated by Django 3.2.15 on 2022-11-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0062_auto_20221028_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3file',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
