# Generated by Django 3.2.15 on 2022-11-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0063_s3file_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='remotefile',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serverfile',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
