# Generated by Django 3.2.18 on 2023-02-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0064_delete_wrong_labels'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('project', 'name', 'parent'), ('task', 'name', 'parent')},
        ),
    ]
