# Generated by Django 3.2.15 on 2023-02-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0065_task_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotefile',
            name='file',
            field=models.CharField(max_length=2048),
        ),
    ]
