# Generated by Django 3.2.18 on 2023-03-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0065_auto_20230221_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudstorage',
            name='credentials',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cloudstorage',
            unique_together=set(),
        ),
    ]
