# Generated by Django 3.2.15 on 2023-04-14 07:33

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0066_alter_remotefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(10, 'LOWEST'), (20, 'LOW'), (30, 'MEDIUM'), (40, 'HIGH'), (50, 'HIGHEST')], default=cvat.apps.engine.models.Priority['MEDIUM']),
        ),
    ]
