# Generated by Django 4.2.1 on 2023-06-06 13:05

import cvat.apps.engine.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0067_alter_cloudstorage_credentials_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=cvat.apps.engine.models.SafeCharField(default="", max_length=1400),
        ),
    ]
