# Generated by Django 3.2.18 on 2023-04-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0068_auto_20230406_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationConflictsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_last_updated', models.DateTimeField()),
                ('gt_job_last_updated', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_conflict_reports', to='engine.job')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('missing_annotation', 'MISSING_ANNOTATION'), ('extra_annotation', 'EXTRA_ANNOTATION'), ('mismatching_annotation', 'MISMATCHING_ANNOTATION')], max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=1024)),
                ('data', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='engine.annotationconflictsreport')),
            ],
        ),
    ]
