# Generated by Django 3.2.18 on 2023-06-07 13:27

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0070_alter_annotationguide_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='access_type',
            field=models.CharField(choices=[('ANONYMOUS_ACCESS', 'ANONYMOUS_ACCESS'), ('PRIVATE_ACCESS', 'PRIVATE_ACCESS')], default=cvat.apps.engine.models.AssetAccessType['PRIVATE_ACCESS'], max_length=16),
        ),
    ]
