# Generated by Django 3.2.18 on 2023-04-22 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0071_job_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('target_last_updated', models.DateTimeField()),
                ('gt_last_updated', models.DateTimeField()),
                ('data', models.JSONField()),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='engine.job')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='engine.qualityreport')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='engine.task')),
            ],
        ),
        migrations.AlterField(
            model_name='annotationconflict',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='engine.qualityreport'),
        ),
        migrations.DeleteModel(
            name='AnnotationConflictsReport',
        ),
    ]
