# Generated by Django 3.2.18 on 2023-04-26 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0072_auto_20230422_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationconflict',
            name='data',
        ),
        migrations.RemoveField(
            model_name='annotationconflict',
            name='message',
        ),
        migrations.AlterField(
            model_name='annotationconflict',
            name='type',
            field=models.CharField(choices=[('missing_annotation', 'MISSING_ANNOTATION'), ('extra_annotation', 'EXTRA_ANNOTATION'), ('mismatching_label', 'MISMATCHING_LABEL')], max_length=32),
        ),
        migrations.CreateModel(
            name='AnnotationId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_id', models.PositiveIntegerField()),
                ('job_id', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('rectangle', 'RECTANGLE'), ('polygon', 'POLYGON'), ('polyline', 'POLYLINE'), ('points', 'POINTS'), ('ellipse', 'ELLIPSE'), ('cuboid', 'CUBOID'), ('mask', 'MASK'), ('skeleton', 'SKELETON')], max_length=32)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_ids', to='engine.annotationconflict')),
            ],
        ),
    ]
