# Generated by Django 4.2.1 on 2023-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0073_alter_attributespec_default_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationguide",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]