# Generated by Django 3.2.18 on 2023-04-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0073_auto_20230426_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationconflict',
            old_name='frame_id',
            new_name='frame',
        ),
    ]
