# Generated by Django 4.2.1 on 2023-07-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0074_alter_labeledimage_source_alter_labeledshape_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationguide",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
