# Generated by Django 3.2.18 on 2023-04-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0074_rename_frame_id_annotationconflict_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationconflict',
            name='type',
            field=models.CharField(choices=[('missing_annotation', 'MISSING_ANNOTATION'), ('extra_annotation', 'EXTRA_ANNOTATION'), ('mismatching_label', 'MISMATCHING_LABEL'), ('low_overlap', 'LOW_OVERLAP')], max_length=32),
        ),
    ]
