# Generated by Django 4.2.6 on 2024-01-25 07:16

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0075_annotationguide_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledshape",
            name="transcript",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="transcript",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="data",
            name="compressed_chunk_type",
            field=models.CharField(
                choices=[
                    ("video", "VIDEO"),
                    ("audio", "AUDIO"),
                    ("imageset", "IMAGESET"),
                    ("list", "LIST"),
                ],
                default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="original_chunk_type",
            field=models.CharField(
                choices=[
                    ("video", "VIDEO"),
                    ("audio", "AUDIO"),
                    ("imageset", "IMAGESET"),
                    ("list", "LIST"),
                ],
                default=cvat.apps.engine.models.DataChoice["IMAGESET"],
                max_length=32,
            ),
        ),
    ]
