# Generated by Django 4.2.1 on 2023-09-04 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0075_annotationguide_is_public"),
    ]

    # https://docs.djangoproject.com/en/3.2/howto/writing-migrations/#migrations-that-add-unique-fields
    operations = [
        migrations.AddField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
