# Generated by Django 3.2.18 on 2023-05-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0076_alter_annotationid_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationconflict',
            name='type',
            field=models.CharField(choices=[('missing_annotation', 'MISSING_ANNOTATION'), ('extra_annotation', 'EXTRA_ANNOTATION'), ('mismatching_label', 'MISMATCHING_LABEL'), ('low_overlap', 'LOW_OVERLAP'), ('mismatching_direction', 'MISMATCHING_DIRECTION')], max_length=32),
        ),
    ]
