# Generated by Django 4.2.6 on 2024-02-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0076_labeledshape_transcript_trackedshape_transcript_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAudioAnnotation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start", models.FloatField()),
                ("end", models.FloatField()),
                ("text", models.TextField()),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.job"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
