# Generated by Django 4.2.1 on 2023-09-04 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0076_project_uuid_generate_default_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
