# Generated by Django 4.2.1 on 2023-09-04 16:55

from django.db import migrations
import uuid

def generate_project_uuid(apps, schema_editor):
    Project = apps.get_model('engine', 'Project')
    queryset = Project.objects.all()
    for p in queryset:
        p.uuid = uuid.uuid4()
    Project.objects.bulk_update(queryset, fields=['uuid'], batch_size=500)

class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0076_project_uuid_initial_migration"),
    ]

    operations = [
        migrations.RunPython(code=generate_project_uuid),
    ]
