# Generated by Django 4.2.11 on 2024-05-23 09:45

from django.db import migrations

def fix_checkbox_values(apps, schema_editor):
    Attribute = apps.get_model('engine', 'AttributeSpec')
    for attribute in Attribute.objects.filter(input_type='checkbox'):
        if attribute.default_value not in ['true', 'false']:
            attribute.default_value = 'false'
        if attribute.values not in ['true', 'false']:
            if  attribute.values == ['']:
                # empty values('') 
                attribute.values = 'false'
            else:
                # if the attribute contained some number or string value then convert it to true
                attribute.values = 'true'
            attribute.save()

class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [migrations.RunPython(fix_checkbox_values)]
