# Generated by Django 4.2.11 on 2024-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="parent_job_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="consensus_jobs_per_segment",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
