# Generated by Django 4.2.6 on 2024-03-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributespec",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
