# Generated by Django 4.2.11 on 2024-04-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributespec",
            name="values",
            field=models.CharField(blank=True, max_length=8192),
        ),
    ]
