# Generated by Django 3.2.18 on 2023-05-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0078_alter_annotationconflict_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationconflict',
            name='type',
            field=models.CharField(choices=[('missing_annotation', 'MISSING_ANNOTATION'), ('extra_annotation', 'EXTRA_ANNOTATION'), ('mismatching_label', 'MISMATCHING_LABEL'), ('low_overlap', 'LOW_OVERLAP'), ('mismatching_direction', 'MISMATCHING_DIRECTION'), ('mismatching_attributes', 'MISMATCHING_ATTRIBUTES'), ('mismatching_groups', 'MISMATCHING_GROUPS'), ('covered_annotation', 'COVERED_ANNOTATION')], max_length=32),
        ),
    ]
