# Generated by Django 4.2.11 on 2024-04-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributespec",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
