# Generated by Django 4.2.11 on 2024-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0078_alter_cloudstorage_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="source_job_id",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="consensus_job_per_segment",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
