# Generated by Django 3.2.18 on 2023-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0079_alter_annotationconflict_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationconflict',
            name='importance',
            field=models.CharField(choices=[('warning', 'WARNING'), ('error', 'ERROR')], default='error', max_length=32),
            preserve_default=False,
        ),
    ]
