# Generated by Django 4.2.6 on 2024-04-05 04:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0079_labeledimage_age_labeledimage_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labeledimage",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="labeledshape",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="labeledtrack",
            name="locale",
        ),
        migrations.RemoveField(
            model_name="trackedshape",
            name="locale",
        ),
    ]
