# Generated by Django 4.2.11 on 2024-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_attributespec_updated_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributespec",
            options={"default_permissions": (), "ordering": ["-display_order"]},
        ),
        migrations.AddField(
            model_name="attributespec",
            name="display_order",
            field=models.IntegerField(default=0),
        ),
    ]
