# Generated by Django 4.2.11 on 2024-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_alter_attributespec_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributespec",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
