# Generated by Django 4.2.11 on 2024-05-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_job_source_job_id_task_consensus_job_per_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="source_job_id",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
