# Generated by Django 4.2.13 on 2024-07-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_validationparams_validationimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="is_placeholder",
            field=models.BooleanField(default=False),
        ),
    ]
