# Generated by Django 4.2.13 on 2024-07-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_alter_labeledimageattributeval_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackedshape",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shapes",
                related_query_name="shape",
                to="engine.labeledtrack",
            ),
        ),
    ]
