# Generated by Django 4.2.13 on 2024-07-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0080_image_is_placeholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="real_frame_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
