# Generated by Django 4.2.11 on 2024-05-30 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0080_alter_job_source_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="source_job_id",
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
