# Generated by Django 3.2.18 on 2023-05-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0080_annotationconflict_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualitySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iou_threshold', models.FloatField()),
                ('oks_sigma', models.FloatField()),
                ('line_thickness', models.FloatField()),
                ('low_overlap_threshold', models.FloatField()),
                ('oriented_lines', models.BooleanField()),
                ('line_orientation_threshold', models.FloatField()),
                ('compare_groups', models.BooleanField()),
                ('group_match_threshold', models.FloatField()),
                ('check_covered_annotations', models.BooleanField()),
                ('object_visibility_threshold', models.FloatField()),
                ('panoptic_comparison', models.BooleanField()),
                ('compare_attributes', models.BooleanField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_settings', to='engine.task')),
            ],
        ),
    ]
