# Generated by Django 4.2.11 on 2024-05-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0080_alter_attributespec_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributespec",
            options={"default_permissions": (), "ordering": ["display_order"]},
        ),
    ]
