# Generated by Django 4.2.6 on 2024-04-05 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0081_labeledimage_audio_locale_labeledshape_audio_locale_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labeledimage",
            old_name="audio_locale",
            new_name="locale",
        ),
        migrations.RenameField(
            model_name="labeledshape",
            old_name="audio_locale",
            new_name="locale",
        ),
        migrations.RenameField(
            model_name="labeledtrack",
            old_name="audio_locale",
            new_name="locale",
        ),
        migrations.RenameField(
            model_name="trackedshape",
            old_name="audio_locale",
            new_name="locale",
        ),
    ]
