# Generated by Django 3.2.18 on 2023-05-12 09:19

import cvat.apps.engine.models
from django.db import migrations, models


def rename_normal_to_annotation(apps, schema_editor):
    Job = apps.get_model("engine", "Job")

    jobs = Job.objects.select_related('segment').all()
    for job in jobs:
        if job.type == 'normal':
            job.type = 'annotation'

    Job.objects.bulk_update(jobs, fields=['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0081_qualitysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('normal', 'NORMAL'), ('annotation', 'ANNOTATION'), ('ground_truth', 'GROUND_TRUTH')], default=cvat.apps.engine.models.JobType['ANNOTATION'], max_length=32),
        ),
        migrations.RunPython(rename_normal_to_annotation),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('annotation', 'ANNOTATION'), ('ground_truth', 'GROUND_TRUTH')], default=cvat.apps.engine.models.JobType['ANNOTATION'], max_length=32),
        ),

    ]
