# Generated by Django 4.2.11 on 2024-05-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0081_alter_attributespec_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributespec",
            name="updated_time",
        ),
    ]
