# Generated by Django 4.2.13 on 2024-08-12 09:49

import os
from django.db import migrations
from cvat.apps.engine.log import get_migration_logger, get_migration_log_dir

def switch_tasks_with_static_chunks_to_dynamic_chunks(apps, schema_editor):
    migration_name = os.path.splitext(os.path.basename(__file__))[0]
    migration_log_dir = get_migration_log_dir()
    with get_migration_logger(migration_name) as common_logger:
        Data = apps.get_model("engine", "Data")

        data_with_static_cache_query = (
            Data.objects
            .filter(storage_method="file_system")
        )

        data_with_static_cache_ids = list(
            v[0]
            for v in (
                data_with_static_cache_query
                .order_by('id')
                .values_list('id')
                .iterator(chunk_size=100000)
            )
        )

        data_with_static_cache_query.update(storage_method="cache")

        updated_ids_filename = os.path.join(migration_log_dir, migration_name + "-data_ids.log")
        with open(updated_ids_filename, "w") as data_ids_file:
            print(
                "The following Data ids have been switched from using \"filesystem\" chunk storage "
                "to \"cache\":",
                file=data_ids_file
            )
            for data_id in data_with_static_cache_ids:
                print(data_id, file=data_ids_file)

        common_logger.info(
            "Information about migrated tasks is available in the migration log file: "
            "{}. You will need to remove data manually for these tasks.".format(
                updated_ids_filename
            )
        )

class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0082_alter_labeledimage_job_and_more"),
    ]

    operations = [
        migrations.RunPython(switch_tasks_with_static_chunks_to_dynamic_chunks)
    ]
