# Generated by Django 4.2.6 on 2024-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0082_rename_audio_locale_labeledimage_locale_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledimage",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledimage",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="emotion",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="accent",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="trackedshape",
            name="emotion",
            field=models.TextField(default=""),
        ),
    ]
