# Generated by Django 4.2.15 on 2024-09-25 13:52

from django.db import migrations, models


def init_chunks_updated_date(apps, schema_editor):
    Segment = apps.get_model("engine", "Segment")
    Segment.objects.update(
        chunks_updated_date=models.Subquery(
            Segment.objects
            .select_related("task")
            .filter(pk=models.OuterRef("pk"))
            .values('task__created_date')[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0084_honeypot_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="chunks_updated_date",
            field=models.DateTimeField(default=None, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            init_chunks_updated_date,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="segment",
            name="chunks_updated_date",
            field=models.DateTimeField(null=False),
        ),
    ]
