# Generated by Django 4.2.6 on 2024-04-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0084_job_ai_audio_annotation_error_msg_and_more"),
    ]

    operations = [
    ]
