# Generated by Django 4.2.11 on 2024-05-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0085_alter_data_consensus_job_per_segment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="consensus_job_per_segment",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
