# Generated by Django 4.2.6 on 2024-04-10 06:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0085_alter_job_ai_audio_annotation_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="ai_audio_annotation_task_id",
            new_name="ai_audio_annotation_background_task_id",
        ),
    ]
