# Generated by Django 4.2.16 on 2024-10-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0085_segment_chunks_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_analytics_access",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can access /analytics.",
                verbose_name="has /analytics access",
            ),
        ),
    ]
