# Generated by Django 4.2.6 on 2024-04-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0085_alter_task_total_audio_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="segment_duration",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
