# Generated by Django 4.2.16 on 2025-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0086_profile_has_analytics_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisMigration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
