# Generated by Django 4.2.15 on 2024-12-11 17:13

import cvat.apps.engine.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0086_profile_has_analytics_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationlayout",
            name="task_data",
            field=cvat.apps.engine.models.NullableOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validation_layout",
                to="engine.data",
            ),
        ),
    ]
