# Generated by Django 4.2.6 on 2024-05-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0086_task_segment_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="audio_total_duration",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
