# Generated by Django 4.2.17 on 2025-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0086_profile_has_analytics_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedisMigration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("app_label", models.CharField(max_length=256)),
                ("name", models.CharField(max_length=256)),
                ("applied_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="redismigration",
            constraint=models.UniqueConstraint(
                fields=("app_label", "name"), name="migration_name_unique"
            ),
        ),
    ]
