# Generated by Django 4.2.15 on 2024-12-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0086_profile_has_analytics_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="last_export_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="last_export_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="last_export_date",
            field=models.DateTimeField(null=True),
        ),
    ]
