# Generated by Django 4.2.6 on 2024-04-10 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0087_alter_job_ai_audio_annotation_background_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="ai_audio_annotation_background_task_id",
        ),
    ]
