# Generated by Django 4.2.11 on 2024-06-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0087_data_agreement_score_threshold_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="source_job_id",
            new_name="parent_job_id",
        ),
        migrations.AlterField(
            model_name="data",
            name="consensus_job_per_segment",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
