# Generated by Django 4.2.11 on 2024-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0088_rename_source_job_id_job_parent_job_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="agreement_score_threshold",
        ),
        migrations.RemoveField(
            model_name="data",
            name="consensus_job_per_segment",
        ),
        migrations.AddField(
            model_name="task",
            name="agreement_score_threshold",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="consensus_job_per_segment",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
