# Generated by Django 4.2.21 on 2025-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0088_consensus_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="content_size",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="data",
            name="content_size",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
