# Generated by Django 4.2.21 on 2025-05-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0089_alter_labeledimage_source_alter_labeledshape_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="content_size",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="data",
            name="content_size",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
