# Generated by Django 4.2.21 on 2025-06-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0090_asset_content_size_data_content_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_activity_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
