# Generated by Django 4.2.6 on 2024-04-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0090_alter_job_ai_audio_annotation_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="ai_audio_annotation_error_msg",
            field=models.CharField(blank=True, default="", max_length=4096, null=True),
        ),
    ]
