# Generated by Django 4.2.21 on 2025-07-07 09:30

import django.db.models.deletion
from django.db import connection, migrations, models


def set_attributeval_job_id(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE engine_labeledimageattributeval AS attrval
            SET job_id = image.job_id
            FROM engine_labeledimage AS image
            WHERE attrval.image_id = image.id;
            """
        )

        cursor.execute(
            """
            UPDATE engine_labeledshapeattributeval AS attrval
            SET job_id = shape.job_id
            FROM engine_labeledshape AS shape
            WHERE attrval.shape_id = shape.id;
            """
        )

        cursor.execute(
            """
            UPDATE engine_labeledtrackattributeval AS attrval
            SET job_id = track.job_id
            FROM engine_labeledtrack AS track
            WHERE attrval.track_id = track.id;
            """
        )

        cursor.execute(
            """
            UPDATE engine_trackedshapeattributeval AS attrval
            SET job_id = track.job_id
            FROM engine_trackedshape AS shape
            JOIN engine_labeledtrack AS track ON shape.track_id = track.id
            WHERE attrval.shape_id = shape.id;
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0091_profile_last_activity_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledimageattributeval",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.AddField(
            model_name="labeledshapeattributeval",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.AddField(
            model_name="labeledtrackattributeval",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.AddField(
            model_name="trackedshapeattributeval",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.RunPython(set_attributeval_job_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="labeledimageattributeval",
            name="job",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.AlterField(
            model_name="labeledshapeattributeval",
            name="job",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.AlterField(
            model_name="labeledtrackattributeval",
            name="job",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
        migrations.AlterField(
            model_name="trackedshapeattributeval",
            name="job",
            field=models.ForeignKey(
                null=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="engine.job",
            ),
        ),
    ]
