# Generated by Django 4.2.25 on 2025-10-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0093_issue_assignee_updated_date_alter_issue_assignee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudstorage",
            name="provider_type",
            field=models.CharField(
                choices=[
                    ("AWS_S3_BUCKET", "Amazon S3"),
                    ("AZURE_CONTAINER", "Azure Blob Storage"),
                    ("GOOGLE_CLOUD_STORAGE", "Google Cloud Storage"),
                ],
                max_length=20,
            ),
        ),
    ]
