# Generated by Django 4.2.26 on 2026-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledimage",
            name="score",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="score",
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="score",
            field=models.FloatField(default=1),
        ),
    ]
