# Generated by Django 4.2.26 on 2025-11-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_invitation_sent_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRegistry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Unique model identifier",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable model name", max_length=256
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0",
                        help_text="Model version (semantic versioning)",
                        max_length=64,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("PYTORCH", "PYTORCH"),
                            ("TENSORFLOW", "TENSORFLOW"),
                            ("ONNX", "ONNX"),
                            ("TENSORRT", "TENSORRT"),
                            ("KERAS", "KERAS"),
                            ("SCIKIT_LEARN", "SCIKIT_LEARN"),
                            ("XGBOOST", "XGBOOST"),
                            ("LIGHTGBM", "LIGHTGBM"),
                            ("OTHER", "OTHER"),
                        ],
                        help_text="ML framework",
                        max_length=32,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("DETECTOR", "DETECTOR"),
                            ("CLASSIFIER", "CLASSIFIER"),
                            ("SEGMENTATION", "SEGMENTATION"),
                            ("KEYPOINT", "KEYPOINT"),
                            ("TRACKER", "TRACKER"),
                            ("REID", "REID"),
                            ("POSE_ESTIMATION", "POSE_ESTIMATION"),
                            ("OTHER", "OTHER"),
                        ],
                        help_text="Type of model",
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Model description"
                    ),
                ),
                (
                    "drive_folder_id",
                    models.CharField(
                        db_index=True,
                        help_text="Google Drive folder ID",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "drive_file_id",
                    models.CharField(
                        db_index=True,
                        help_text="Google Drive model file ID",
                        max_length=128,
                    ),
                ),
                (
                    "model_filename",
                    models.CharField(help_text="Name of model file", max_length=256),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of labels the model predicts",
                    ),
                ),
                (
                    "input_shape",
                    models.JSONField(
                        blank=True,
                        help_text="Expected input dimensions",
                        null=True,
                    ),
                ),
                (
                    "output_spec",
                    models.JSONField(
                        blank=True,
                        help_text="Output format specification",
                        null=True,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Tags for categorization"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model author/creator",
                        max_length=256,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this model belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="models",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="models",
                        related_query_name="model",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "engine_modelregistry",
                "ordering": ["-updated_date"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Version identifier", max_length=64),
                ),
                (
                    "drive_file_id",
                    models.CharField(
                        db_index=True,
                        help_text="Google Drive file ID for this version",
                        max_length=128,
                    ),
                ),
                (
                    "model_filename",
                    models.CharField(
                        help_text="Name of model file for this version", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Version-specific notes"
                    ),
                ),
                (
                    "labels",
                    models.JSONField(
                        blank=True, default=list, help_text="Labels for this version"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this version is active/current"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Parent model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="engine.modelregistry",
                    ),
                ),
            ],
            options={
                "db_table": "engine_modelversion",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="ModelDownloadLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True,
                        help_text="Downloaded file size in bytes",
                        null=True,
                    ),
                ),
                (
                    "download_duration",
                    models.FloatField(
                        blank=True,
                        help_text="Download duration in seconds",
                        null=True,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Purpose: inference, training, etc.",
                        max_length=64,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Downloaded model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloads",
                        to="engine.modelregistry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who downloaded the model",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "engine_modeldownloadlog",
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="modelregistry",
            index=models.Index(fields=["name"], name="engine_mode_name_3eee8a_idx"),
        ),
        migrations.AddIndex(
            model_name="modelregistry",
            index=models.Index(
                fields=["framework"], name="engine_mode_framewo_fbc6e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelregistry",
            index=models.Index(
                fields=["model_type"], name="engine_mode_model_t_85e2c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelregistry",
            index=models.Index(
                fields=["-updated_date"], name="engine_mode_updated_f9a2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["model", "-created_date"],
                name="engine_mode_model_i_6d4b1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(fields=["version"], name="engine_mode_version_3c7e9f_idx"),
        ),
        migrations.AddIndex(
            model_name="modeldownloadlog",
            index=models.Index(
                fields=["model", "-downloaded_at"],
                name="engine_mode_model_i_8a3f1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="modeldownloadlog",
            index=models.Index(
                fields=["user", "-downloaded_at"],
                name="engine_mode_user_id_7c5d2b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="modelversion",
            unique_together={("model", "version")},
        ),
    ]
