# Generated by Django 4.2.26 on 2026-02-09 12:06

from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Concat, Length, Substr

path_prefix = Concat(
    models.Value(settings.MEDIA_DATA_ROOT.as_posix() + "/"), "data_id", models.Value("/raw/")
)


def make_path_relative(apps, schema_editor):
    RelatedFile = apps.get_model("engine", "RelatedFile")

    # Before we chop off the prefix, let's make sure it's actually there.
    if files_without_prefix := RelatedFile.objects.exclude(path__startswith=path_prefix)[:10]:
        raise RuntimeError(
            "Found RelatedFile objects with unexpected paths. Example IDs: "
            + " ".join(str(f.id) for f in files_without_prefix)
        )

    RelatedFile.objects.update(path=Substr("path", Length(path_prefix) + 1))


def make_path_absolute(apps, schema_editor):
    RelatedFile = apps.get_model("engine", "RelatedFile")
    RelatedFile.objects.update(path=Concat(path_prefix, "path"))


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0096_add_annotation_score_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatedfile",
            name="path",
            field=models.CharField(max_length=1024),
        ),
        migrations.RunPython(make_path_relative, make_path_absolute),
    ]
