# Generated by Django 4.2.26 on 2026-02-05 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0097_alter_relatedfile_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="local_storage_backing_cs",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="engine.cloudstorage",
            ),
        ),
    ]
