# Generated by Django 4.2.26 on 2026-02-16 14:30

from django.db import migrations, models

import cvat.apps.engine.models


def update_consensus_replica_to_replica(apps, schema_editor):
    Job = apps.get_model("engine", "Job")
    Job.objects.filter(type="consensus_replica").update(type="replica")


def update_replica_to_consensus_replica(apps, schema_editor):
    Job = apps.get_model("engine", "Job")
    Job.objects.filter(type="replica").update(type="consensus_replica")


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0097_alter_relatedfile_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="consensus_replicas",
            new_name="initial_replicas",
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("annotation", "ANNOTATION"),
                    ("ground_truth", "GROUND_TRUTH"),
                    ("consensus_replica", "CONSENSUS_REPLICA"),
                    ("replica", "REPLICA"),
                ],
                default=cvat.apps.engine.models.JobType["ANNOTATION"],
                max_length=32,
            ),
        ),
        migrations.RunPython(
            code=update_consensus_replica_to_replica,
            reverse_code=update_replica_to_consensus_replica,
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("annotation", "ANNOTATION"),
                    ("ground_truth", "GROUND_TRUTH"),
                    ("replica", "REPLICA"),
                ],
                default=cvat.apps.engine.models.JobType["ANNOTATION"],
                max_length=32,
            ),
        ),
    ]
