# Generated by Django 4.2.26 on 2026-02-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0097_alter_relatedfile_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="consensus_replicas",
            new_name="initial_replicas",
        ),
    ]
