# Generated by Django 4.2.26 on 2026-04-24 17:06

from django.db import migrations, models


def validate_task_mode(apps, schema_editor):
    Task = apps.get_model("engine", "Task")

    ALLOWED_MODES = ("", "annotation", "interpolation")

    invalid_rows = (
        Task.objects.exclude(mode__in=ALLOWED_MODES)
        .order_by("-id")
        .values_list("id", flat=True)[:10]
    )

    if invalid_rows:
        raise Exception(
            "Some '{}' table rows have unexpected 'mode' column values. Allowed modes: {}. "
            "Please review the related tasks and remove them, if possible. "
            "Example Task ids: {}".format(
                Task._meta.db_table,
                ", ".join(f"'{v}'" for v in ALLOWED_MODES),
                ", ".join(f"{v}" for v in invalid_rows),
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0099_remove_chunk_type_list"),
    ]

    operations = [
        migrations.RunPython(validate_task_mode, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="task",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("annotation", "Annotation"), ("interpolation", "Interpolation")],
                default="",
                max_length=32,
            ),
        ),
    ]
