# Generated by Django 4.2.26 on 2026-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0099_audiochunkinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="has_cover_image",
            field=models.BooleanField(default=False),
        ),
    ]
