# Generated by Django 4.2.26 on 2026-04-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0099_remove_chunk_type_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("annotation", "Annotation"), ("interpolation", "Interpolation")],
                default="",
                max_length=32,
            ),
        ),
    ]
