# Generated by Django 4.2.26 on 2026-05-05 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0100_alter_task_mode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labeledimage",
            options={},
        ),
        migrations.AlterModelOptions(
            name="labeledshape",
            options={},
        ),
        migrations.AlterModelOptions(
            name="labeledtrack",
            options={},
        ),
        migrations.AlterModelOptions(
            name="trackedshape",
            options={},
        ),
    ]
