# Generated by Django 4.2.26 on 2026-03-31 14:16

import django.db.models.deletion
from django.db import migrations, models

import cvat.apps.engine.models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0100_audio_has_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabeledInterval",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("group", models.PositiveIntegerField(null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("auto", "AUTO"),
                            ("semi-auto", "SEMI_AUTO"),
                            ("manual", "MANUAL"),
                            ("file", "FILE"),
                            ("consensus", "CONSENSUS"),
                        ],
                        default="manual",
                        max_length=16,
                        null=True,
                    ),
                ),
                ("score", models.FloatField(default=1)),
                ("start", models.PositiveIntegerField()),
                ("stop", models.PositiveIntegerField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="engine.job"
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.label"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LabeledIntervalAttributeVal",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", cvat.apps.engine.models.SafeCharField(max_length=4096)),
                (
                    "interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="attributes",
                        related_query_name="attribute",
                        to="engine.labeledinterval",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="engine.job"
                    ),
                ),
                (
                    "spec",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.attributespec"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
