# Generated by Django 4.2.26 on 2026-04-29 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0102_alter_default_chunk_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="image_quality",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="dimension",
            field=models.CharField(
                blank=True,
                choices=[("1d", "DIM_1D"), ("2d", "DIM_2D"), ("3d", "DIM_3D")],
                default="",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                ("sampling_rate", models.PositiveIntegerField()),
                ("has_cover_image", models.BooleanField(default=False)),
                (
                    "data",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio",
                        to="engine.data",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
