# Generated by Django 4.2.26 on 2026-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0102_add_task_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="compressed_chunk_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "VIDEO"), ("imageset", "IMAGESET")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="original_chunk_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "VIDEO"), ("imageset", "IMAGESET")],
                default="",
                max_length=32,
            ),
        ),
    ]
