# Generated by Django 4.2.26 on 2026-05-04 14:43

import django.db.models.deletion
from django.db import migrations, models


def initialize_chunks_in_audio_tasks(apps, schema_editor):
    Data = apps.get_model("engine", "Data")

    Data.objects.filter(
        task__media_type="audio", compressed_chunk_type="", original_chunk_type=""
    ).update(compressed_chunk_type="audio_mp3", original_chunk_type="audio_mp3")


def revert_audio_chunks(apps, schema_editor):
    Data = apps.get_model("engine", "Data")

    Data.objects.filter(
        task__media_type="audio", compressed_chunk_type="audio_mp3", original_chunk_type="audio_mp3"
    ).update(compressed_chunk_type="", original_chunk_type="")


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0104_add_audio_support"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="compressed_chunk_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "VIDEO"), ("imageset", "IMAGESET"), ("audio_mp3", "AUDIO_MP3")],
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="original_chunk_type",
            field=models.CharField(
                blank=True,
                choices=[("video", "VIDEO"), ("imageset", "IMAGESET"), ("audio_mp3", "AUDIO_MP3")],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(initialize_chunks_in_audio_tasks, reverse_code=revert_audio_chunks),
        migrations.CreateModel(
            name="AudioChunkInfo",
            fields=[
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("right_padding", models.PositiveIntegerField(default=0)),
                (
                    "audio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        related_query_name="chunk",
                        to="engine.audio",
                    ),
                ),
                (
                    "data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_chunks",
                        related_query_name="audio_chunk",
                        to="engine.data",
                    ),
                ),
            ],
        ),
    ]
