# Generated by Django 5.2.14 on 2026-07-07 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
        ("organizations", "0002_invitation_sent_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="unique_task_name",
                violation_error_message="A task with this name already exists.",
            ),
        ),
    ]
