# Generated by Django 5.2.14 on 2026-07-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledimage",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labeledinterval",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labeledshape",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="labeledtrack",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="labeledimage",
            constraint=models.UniqueConstraint(
                fields=("job", "uuid"), name="engine_labeledimage_unique_job_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="labeledinterval",
            constraint=models.UniqueConstraint(
                fields=("job", "uuid"), name="engine_labeledinterval_unique_job_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="labeledshape",
            constraint=models.UniqueConstraint(
                fields=("job", "uuid"), name="engine_labeledshape_unique_job_uuid"
            ),
        ),
        migrations.AddConstraint(
            model_name="labeledtrack",
            constraint=models.UniqueConstraint(
                fields=("job", "uuid"), name="engine_labeledtrack_unique_job_uuid"
            ),
        ),
    ]
