# Generated by Django 5.2.14 on 2026-07-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationguide",
            name="is_public",
        ),
    ]
