# Generated by Django 5.2.14 on 2026-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudstorage",
            name="credentials_type",
            field=models.CharField(
                choices=[
                    ("KEY_SECRET_KEY_PAIR", "KEY_SECRET_KEY_PAIR"),
                    ("ACCOUNT_NAME_TOKEN_PAIR", "ACCOUNT_NAME_TOKEN_PAIR"),
                    ("KEY_FILE_PATH", "KEY_FILE_PATH"),
                    ("ANONYMOUS_ACCESS", "ANONYMOUS_ACCESS"),
                    ("CONNECTION_STRING", "CONNECTION_STRING"),
                    ("SERVICE_PRINCIPAL_CERT", "SERVICE_PRINCIPAL_CERT"),
                ],
                max_length=29,
            ),
        ),
    ]
