# Copyright (C) 2018-2022 Intel Corporation
# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

name: cvat_audio

x-backend-env: &backend-env
  CVAT_POSTGRES_HOST: cvat_db_audio
  CVAT_REDIS_INMEM_HOST: cvat_redis_inmem_audio
  CVAT_REDIS_INMEM_PORT: 6379
  CVAT_REDIS_ONDISK_HOST: cvat_redis_ondisk_audio
  CVAT_REDIS_ONDISK_PORT: 6666
  CVAT_LOG_IMPORT_ERRORS: 'true'
  CVAT_ALLOW_STATIC_CACHE: '${CVAT_ALLOW_STATIC_CACHE:-no}'
  DJANGO_LOG_SERVER_HOST: cvat_vector_audio
  DJANGO_LOG_SERVER_PORT: 8282
  no_proxy: cvat_clickhouse_audio,cvat_grafana_audio,cvat_vector_audio,nuclio,opa_audio,${no_proxy:-}
  SMOKESCREEN_OPTS: ${SMOKESCREEN_OPTS:-}

x-backend-deps: &backend-deps
  cvat_redis_inmem_audio:
    condition: service_started
  cvat_redis_ondisk_audio:
    condition: service_started
  cvat_db_audio:
    condition: service_started
  cvat_clickhouse_audio:
    condition: service_started

x-clickhouse-env: &clickhouse-env
  CLICKHOUSE_HOST: cvat_clickhouse_audio
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_DB: cvat
  CLICKHOUSE_USER: user
  CLICKHOUSE_PASSWORD: user

services:
  cvat_db_audio:
    container_name: cvat_db_audio
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: cvat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - cvat_db_audio:/var/lib/postgresql/data
    networks:
      - cvat_audio

  cvat_redis_inmem_audio:
    container_name: cvat_redis_inmem_audio
    image: redis:7.2.11-alpine
    restart: always
    command: [
      "redis-server",
      "--save", "60", "100",
      "--appendonly", "yes",
    ]
    volumes:
      - cvat_inmem_db_audio:/data
    networks:
      - cvat_audio

  cvat_redis_ondisk_audio:
    container_name: cvat_redis_ondisk_audio
    image: apache/kvrocks:2.15.0
    restart: always
    # The kvrocks image a) has a healthcheck command, and b) has a root process
    # that doesn't reap children, so it's susceptible to the problem described here:
    # <https://stackoverflow.com/a/77109064>. Kvrocks also uses a tiny timeout for
    # its healthcheck command (1s), which makes the problem more likely to manifest.
    # Use a separate init process as a workaround.
    init: true
    volumes:
      - cvat_cache_db_audio:/var/lib/kvrocks
    networks:
      - cvat_audio
    command: [
      "--compact-cron", "0 3 * * *",
      ]

  cvat_server_audio:
    container_name: cvat_server_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      <<: *backend-deps
      cvat_opa_audio:
        condition:
          service_started
    environment:
      <<: [*backend-env, *clickhouse-env]
      DJANGO_MODWSGI_EXTRA_ARGS: ''
      ALLOWED_HOSTS: '*'
      ADAPTIVE_AUTO_ANNOTATION: 'false'
      NUMPROCS: 2
      CVAT_ANALYTICS: 1
      CVAT_BASE_URL:
      ONE_RUNNING_JOB_IN_QUEUE_PER_USER:
    command: init run server
    labels:
      cvat.instance: audio
      traefik.enable: "true"
      traefik.docker.network: cvat_audio
      traefik.http.services.cvat_audio.loadbalancer.server.port: "8080"
      traefik.http.routers.cvat_audio.rule:
        Host(`${CVAT_HOST:-localhost}`) &&
        (PathPrefix(`/api/`) || PathPrefix(`/static/`) || PathPrefix(`/admin`)
          || PathPrefix(`/django-rq`))
      traefik.http.routers.cvat_audio.entrypoints: webaudio
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      cvat_audio:
        aliases:
          - cvat-server-audio

  cvat_worker_utils_audio:
    container_name: cvat_worker_utils_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      CVAT_REDIS_INMEM_PASSWORD: ''
      NUMPROCS: 1
    command: run worker notifications cleaning
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_import_audio:
    container_name: cvat_worker_import_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      NUMPROCS: 2
    command: run worker import
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_export_audio:
    container_name: cvat_worker_export_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: [*backend-env, *clickhouse-env]
      NUMPROCS: 2
    command: run worker export
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_annotation_audio:
    container_name: cvat_worker_annotation_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      NUMPROCS: 1
    command: run worker annotation
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_webhooks_audio:
    container_name: cvat_worker_webhooks_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      NUMPROCS: 1
    command: run worker webhooks
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_quality_reports_audio:
    container_name: cvat_worker_quality_reports_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      NUMPROCS: 1
    command: run worker quality_reports
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_chunks_audio:
    container_name: cvat_worker_chunks_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      NUMPROCS: 2
    command: run worker chunks
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_worker_consensus_audio:
    container_name: cvat_worker_consensus_audio
    image: cvat/server:${CVAT_VERSION:-dev}
    restart: always
    depends_on: *backend-deps
    environment:
      <<: *backend-env
      NUMPROCS: 1
    command: run worker consensus
    volumes:
      - cvat_data_audio:/home/django/data
      - cvat_keys_audio:/home/django/keys
      - cvat_logs_audio:/home/django/logs
    networks:
      - cvat_audio

  cvat_ui_audio:
    container_name: cvat_ui_audio
    image: cvat/ui:${CVAT_VERSION:-dev}
    restart: always
    depends_on:
      - cvat_server_audio
    labels:
      cvat.instance: audio
      traefik.enable: "true"
      traefik.docker.network: cvat_audio
      traefik.http.services.cvat_ui_audio.loadbalancer.server.port: "8000"
      traefik.http.routers.cvat_ui_audio.rule: Host(`${CVAT_HOST:-localhost}`)
      traefik.http.routers.cvat_ui_audio.entrypoints: webaudio
    networks:
      - cvat_audio

  traefik_audio:
    image: traefik:v3.6
    container_name: traefik_audio
    restart: always
    ports:
      - 18080:8080
      - 18090:8090
    environment:
      CVAT_HOST: ${CVAT_HOST:-localhost}
      DJANGO_LOG_VIEWER_HOST: cvat_grafana_audio
      DJANGO_LOG_VIEWER_PORT: 3000

      TRAEFIK_ACCESSLOG_FORMAT: json
      TRAEFIK_ACCESSLOG_FIELDS_DEFAULTMODE: drop
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_ClientHost: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_DownstreamContentSize: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_DownstreamStatus: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_Duration: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_RequestHost: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_RequestMethod: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_RequestPath: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_RequestPort: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_RequestProtocol: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_RouterName: keep
      TRAEFIK_ACCESSLOG_FIELDS_NAMES_StartUTC: keep

      TRAEFIK_LOG_FORMAT: json
      TRAEFIK_ENTRYPOINTS_webaudio_ADDRESS: :8080
      TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS: 'Label(`cvat.instance`, `audio`)'
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: cvat_audio
      TRAEFIK_PROVIDERS_FILE_DIRECTORY: /etc/traefik/rules
    # Uncomment to get Traefik dashboard
    #   TRAEFIK_API_DASHBOARD: "true"
    #   TRAEFIK_ENTRYPOINTS_dashboardaudio_ADDRESS: :8090
    # labels:
    #   traefik.enable: "true"
    #   traefik.http.routers.dashboard_audio.entrypoints: dashboardaudio
    #   traefik.http.routers.dashboard_audio.service: api@internal
    #   traefik.http.routers.dashboard_audio.rule: Host(`${CVAT_HOST:-localhost}`)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./components/analytics/grafana_conf_audio.yml:/etc/traefik/rules/grafana_conf.yml:ro
    networks:
      - cvat_audio
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "10"

  cvat_opa_audio:
    container_name: cvat_opa_audio
    image: openpolicyagent/opa:1.12.2
    restart: always
    networks:
      cvat_audio:
        aliases:
          - opa_audio
    command:
      - run
      - --server
      - --addr=:8181
      - --log-level=error
      - --set=services.cvat.url=http://cvat-server-audio:8080
      - --set=bundles.cvat.service=cvat
      - --set=bundles.cvat.resource=/api/auth/rules
      - --set=bundles.cvat.polling.min_delay_seconds=5
      - --set=bundles.cvat.polling.max_delay_seconds=15

  cvat_clickhouse_audio:
    container_name: cvat_clickhouse_audio
    image: clickhouse/clickhouse-server:23.11-alpine
    restart: "always"
    environment:
      <<: *clickhouse-env
    networks:
      - cvat_audio
    volumes:
      - cvat_events_db_audio:/var/lib/clickhouse/

  cvat_vector_audio:
    container_name: cvat_vector_audio
    image: timberio/vector:0.26.0-alpine
    user: "1000:1000" # Workaround for <https://github.com/vectordotdev/vector/issues/1599>.
    restart: always
    depends_on:
      - cvat_clickhouse_audio
    environment:
      <<: *clickhouse-env
    networks:
      - cvat_audio
    volumes:
      - type: bind
        source: ./components/analytics/vector/vector.toml
        target: /etc/vector/vector.toml
        read_only: true
      - type: tmpfs
        target: /vector-data-dir

  cvat_grafana_audio:
    image: grafana/grafana-oss:10.1.2
    restart: always
    container_name: cvat_grafana_audio
    environment:
      <<: *clickhouse-env
      GF_PATHS_PROVISIONING: /etc/grafana/provisioning
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_SERVER_ROOT_URL: http://${CVAT_HOST:-localhost}/analytics
      GF_INSTALL_PLUGINS: 'grafana-clickhouse-datasource 4.8.2'
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /var/lib/grafana/dashboards/all_events.json
    volumes:
      - ./components/analytics/grafana/dashboards/:/var/lib/grafana/dashboards/:ro
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat << 'EOF' > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: 'ClickHouse'
            type: 'grafana-clickhouse-datasource'
            isDefault: true
            jsonData:
              defaultDatabase: $${CLICKHOUSE_DB}
              port: $${CLICKHOUSE_PORT}
              server: $${CLICKHOUSE_HOST}
              username: $${CLICKHOUSE_USER}
              tlsSkipVerify: false
              protocol: http
            secureJsonData:
              password: $${CLICKHOUSE_PASSWORD}
            editable: true
        EOF
        mkdir -p /etc/grafana/provisioning/dashboards
        cat << EOF > /etc/grafana/provisioning/dashboards/dashboard.yaml
        apiVersion: 1
        providers:
          - name: cvat-logs
            type: file
            updateIntervalSeconds: 30
            options:
              path:  /var/lib/grafana/dashboards
              foldersFromFilesStructure: true
        EOF
        exec /run.sh
    networks:
      - cvat_audio

volumes:
  cvat_db_audio:
  cvat_data_audio:
  cvat_keys_audio:
  cvat_logs_audio:
  cvat_inmem_db_audio:
  cvat_events_db_audio:
  cvat_cache_db_audio:

networks:
  cvat_audio:
