# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

x-coverage-environment: &coverage-environment
  COVERAGE_PROCESS_START: /opt/cvat/coverage-bootstrap/.coveragerc
  COVERAGE_FILE: /coverage-data/.coverage
  CVAT_COVERAGE_CONTEXT: '${CVAT_COVERAGE_CONTEXT:-manual}'
  PYTHONPATH: /opt/cvat/coverage-bootstrap

x-coverage-volumes: &coverage-volumes
  - ./tests/python/coverage:/opt/cvat/coverage-bootstrap:ro
  - ./coverage-data:/coverage-data

services:
  cvat_server:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_utils:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_import:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_export:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_annotation:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_webhooks:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_quality_reports:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_chunks:
    environment: *coverage-environment
    volumes: *coverage-volumes

  cvat_worker_consensus:
    environment: *coverage-environment
    volumes: *coverage-volumes
