[pytest]
required_plugins = pytest-timeout pytest-cases
addopts = --verbose --capture=tee-sys

# We expect no regular individual test to run too long
# can be overridden for specific tests with a test decorator
timeout = 15

markers =
    infra_profile(name): Minimum required execution profile: core, extended, full.
    parallel_group(mode): Parallel balancing mode. Use "case" (default), "fixture", "class", or "function".

filterwarnings =
    ignore::DeprecationWarning:cvat_sdk.core
