apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvat-backend-data
  namespace: cvat
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi
