# Generated by Django 4.2.21 on 2025-07-10 17:28

from django.db import migrations
from django.db.models import Count


def delete_email_addresses_for_dummy_users(apps, schema_editor):
    EmailAddress = apps.get_model("account", "EmailAddress")

    # delete EmailAddress records for dummy users that were created by invitations
    EmailAddress.objects.filter(verified=False) \
        .annotate(social_accounts_count=Count("user__socialaccount")) \
        .filter(social_accounts_count=0, user__password__startswith="!") \
        .delete()

def normalize_email_case_mismatches(apps, schema_editor):
    EmailAddress = apps.get_model("account", "EmailAddress")

    # fix case-related mismatches between User.email and EmailAddress.email
    email_addresses = (
        EmailAddress.objects.filter(verified=True)
        .annotate(social_accounts_count=Count("user__socialaccount"))
        .filter(social_accounts_count=0)
        .select_related("user")
    )
    email_addresses_to_update = []

    for email_address in email_addresses:
        user_email = email_address.user.email
        if (
            email_address.email.lower() == user_email.lower()
            and email_address.email != user_email
        ):
            email_address.email = user_email
            email_addresses_to_update.append(email_address)
    EmailAddress.objects.bulk_update(email_addresses_to_update, ["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_remove_business_group"),
    ]

    operations = [
        migrations.RunPython(
            delete_email_addresses_for_dummy_users,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            normalize_email_case_mismatches,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
