# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

# Generated by Django 5.2.16 on 2026-09-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_move_user_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_via",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("social", "Social"),
                    ("sso", "SSO"),
                    ("ldap", "LDAP"),
                    ("invitation", "Invitation"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
