fullnameOverride: "cvat-agent"

# Please replace with your Docker image URL that contains the desired agent implementation.
image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

agent:
  ### Common configuration
  # Please specify the number of agent replicas you want to deploy.
  replicaCount: 1
  # Please specify the organization slug in CVAT if you want to deploy agent under organization. Else leave empty.
  org_slug: ""
  # Please specify if you want to use GPU for your agent. Ensure that you are using a compatible image and your K8s cluster has GPU resources available.
  use_cuda: false
  # Please replace with your actual CVAT instance URL.
  cvat_base_url: "https://app.cvat.ai"
  # You can provide the CVAT access token directly here, but it's recommended to use Kubernetes Secrets for better security.
  # If you choose to use a secret, make sure to create it in your cluster and reference it in the `secret_env` section below.
  # Token takes precedence over the secret, so if both are provided, the value here will be used.
  cvat_access_token: ""

  ### Model configuration

  modelPresets:
    yolo:
      model:
        type: str
        value: "yolo26s.pt"
      keypoint_names_path:
        type: str
        value: ""
    sam2:
      model_id:
        type: str
        value: "facebook/sam2.1-hiera-tiny"
    custom:
      # use modelParamsOverride to specify custom parameters for your model.

  # Please pick a preset for your agent's model configuration. The preset will automatically fill in the necessary parameters for the chosen model type. If you choose a preset, you can still override specific parameters in the `modelParamsOverride` section below.
  # Keys with empty 'value' will be ignored.
  preset: sam2
  modelParamsOverride: { }
#  modelParamsOverride:
#      model:
#        type: str
#        value: "yolo26l.pt"
#      test_value:
#        type: str
#        value: "exampleValue"

  ### Resources and env
  resources:
    limits:
      cpu: 1
#      memory: 1.5Gi
    requests:
      cpu: 200m
      memory: 256Mi
  envVars: []
#    - name: EXAMPLE_ENV_VAR
#      value: true
  secret_env:
    - name: CVAT_ACCESS_TOKEN
      secretName: cvat-agent
      secretKey: token

job:
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 256Mi
  envVars: []
#   - name: EXAMPLE_ENV_VAR
#     value: true
