apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent.fullname" . }}-job-rolebinding
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "agent.fullname" . }}-job-role
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.fullname" . }}-job-sa
    namespace: {{ .Release.Namespace }}
