apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent.fullname" . }}-job-sa
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, pre-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-5"
