services:
  cvat_server:
    build:
      args:
        CVAT_DEBUG_ENABLED: "yes"
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      CVAT_DEBUG_WAIT: "${CVAT_DEBUG_WAIT_CLIENT:-no}"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_utils:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_import:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_export:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_annotation:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_webhooks:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_quality_reports:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_chunks:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_worker_consensus:
    profiles: ["workers"]
    environment:
      CVAT_DEBUG_ENABLED: "yes"
      NUMPROCS: 1
    volumes:
      - ./cvat:/home/django/cvat:delegated
      - ./manage.py:/home/django/manage.py:delegated
      - ./utils:/home/django/utils:delegated

  cvat_vector:
    profiles: ["analytics"]

  cvat_grafana:
    profiles: ["analytics"]
