# Generated by Django 4.2.13 on 2024-07-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "engine",
            "0079_job_parent_job_id_task_consensus_jobs_per_normal_job_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsensusSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_score_threshold", models.FloatField(default=0)),
                ("quorum", models.IntegerField(default=0)),
                ("iou_threshold", models.FloatField(default=0.5)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_settings",
                        to="engine.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsensusReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("target_last_updated", models.DateTimeField()),
                ("data", models.JSONField()),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_reports",
                        to="engine.job",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consensus_reports",
                        to="engine.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsensusConflict",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NO_MATCHING_ITEM", "NoMatchingItemError"),
                            ("FAILED_ATTRIBUTE_VOTING", "FailedAttrVotingError"),
                            ("NO_MATCHING_ANNOTATION", "NoMatchingAnnError"),
                            ("ANNOTATION_TOO_CLOSE", "AnnotationsTooCloseError"),
                            ("WRONG_GROUP", "WrongGroupError"),
                            ("FAILED_LABEL_VOTING", "FailedLabelVotingError"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="consensus.consensusreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationId",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obj_id", models.PositiveIntegerField()),
                ("job_id", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tag", "TAG"),
                            ("shape", "SHAPE"),
                            ("track", "TRACK"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "shape_type",
                    models.CharField(
                        choices=[
                            ("rectangle", "RECTANGLE"),
                            ("polygon", "POLYGON"),
                            ("polyline", "POLYLINE"),
                            ("points", "POINTS"),
                            ("ellipse", "ELLIPSE"),
                            ("cuboid", "CUBOID"),
                            ("mask", "MASK"),
                            ("skeleton", "SKELETON"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "conflict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_ids",
                        to="consensus.consensusconflict",
                    ),
                ),
            ],
        ),
    ]
