# Generated by Django 4.2.26 on 2026-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consensus", "0002_remove_consensussettings_quorum"),
    ]

    operations = [
        migrations.AddField(
            model_name="consensussettings",
            name="quorum",
            field=models.FloatField(default=0.5),
        ),
    ]
