# Generated by Django 4.2.26 on 2025-11-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_invitation_sent_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("engine", "0096_add_model_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly name for the service",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description of the service",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        help_text="Port number allocated to this service"
                    ),
                ),
                (
                    "api_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional API configuration (e.g., batch size, timeout)",
                    ),
                ),
                (
                    "container_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Docker container ID",
                        max_length=128,
                    ),
                ),
                (
                    "container_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Docker container name",
                        max_length=256,
                    ),
                ),
                (
                    "container_status",
                    models.CharField(
                        choices=[
                            ("CREATING", "CREATING"),
                            ("STARTING", "STARTING"),
                            ("RUNNING", "RUNNING"),
                            ("STOPPING", "STOPPING"),
                            ("STOPPED", "STOPPED"),
                            ("FAILED", "FAILED"),
                            ("DELETED", "DELETED"),
                        ],
                        db_index=True,
                        default="CREATING",
                        help_text="Current status of the container",
                        max_length=32,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_date",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the service was last started",
                        null=True,
                    ),
                ),
                (
                    "stopped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the service was stopped",
                        null=True,
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "HEALTHY"),
                            ("UNHEALTHY", "UNHEALTHY"),
                            ("UNKNOWN", "UNKNOWN"),
                        ],
                        default="UNKNOWN",
                        help_text="Health status of the service",
                        max_length=32,
                    ),
                ),
                (
                    "last_health_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last health check",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if service failed",
                    ),
                ),
                (
                    "request_count",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of prediction requests made to this service",
                    ),
                ),
                (
                    "last_request_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last prediction request",
                        null=True,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Model from Model Registry to use for inference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inference_services",
                        to="engine.modelregistry",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the service",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inference_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this service belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inference_services",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="InferenceServiceLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "DEBUG"),
                            ("INFO", "INFO"),
                            ("WARNING", "WARNING"),
                            ("ERROR", "ERROR"),
                            ("CRITICAL", "CRITICAL"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=32,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Log message"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., request_id, duration)",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Inference service this log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="inference_manager.inferenceservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InferencePrediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frame_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Frame number that was predicted",
                        null=True,
                    ),
                ),
                (
                    "request_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "prediction_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of shapes/objects predicted",
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        help_text="Response time in milliseconds"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the prediction was successful",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if prediction failed",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Inference service that made the prediction",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="inference_manager.inferenceservice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who requested the prediction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job where prediction was used (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inference_predictions",
                        to="engine.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-request_timestamp"],
            },
        ),
        # Add indexes for InferenceService
        migrations.AddIndex(
            model_name="inferenceservice",
            index=models.Index(
                fields=["owner", "created_date"],
                name="inference_m_owner_i_3a7e8f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceservice",
            index=models.Index(
                fields=["organization", "created_date"],
                name="inference_m_organiz_4b5c9d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceservice",
            index=models.Index(
                fields=["container_status"],
                name="inference_m_contain_2e6a7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceservice",
            index=models.Index(
                fields=["-updated_date"],
                name="inference_m_updated_9c8d4f_idx",
            ),
        ),
        # Add indexes for InferenceServiceLog
        migrations.AddIndex(
            model_name="inferenceservicelog",
            index=models.Index(
                fields=["service", "-timestamp"],
                name="inference_m_service_5f3e2a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceservicelog",
            index=models.Index(
                fields=["log_level", "-timestamp"],
                name="inference_m_log_lev_7d4b9c_idx",
            ),
        ),
        # Add indexes for InferencePrediction
        migrations.AddIndex(
            model_name="inferenceprediction",
            index=models.Index(
                fields=["service", "-request_timestamp"],
                name="inference_m_service_1a8e6f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceprediction",
            index=models.Index(
                fields=["user", "-request_timestamp"],
                name="inference_m_user_id_2b9d7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inferenceprediction",
            index=models.Index(
                fields=["-request_timestamp"],
                name="inference_m_request_3c5f8a_idx",
            ),
        ),
    ]
