[include]
files = reusable/supervisord.conf %(ENV_CVAT_SUPERVISORD_INCLUDES)s

[program:rqworker-pool]
command=%(ENV_HOME)s/wait_for_deps.sh
    python3 %(ENV_HOME)s/manage.py rqworker-pool -v 3 %(ENV_CVAT_QUEUES)s
        --worker-class cvat.rqworker.DefaultWorker --num-workers %(ENV_NUMWORKERS)s %(ENV_CVAT_RQWORKER_EXTRA_FLAGS)s
environment=VECTOR_EVENT_HANDLER="SynchronousLogstashHandler"
numprocs=%(ENV_NUMPROCS)s
process_name=%(program_name)s-%(process_num)d
autorestart=true
