# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

from .driver import annotate_task
from .exceptions import BadFunctionError
from .interface import (
    AutoAnnotationFunction,
    DetectionAnnotation,
    DetectionFunction,
    DetectionFunctionContext,
    DetectionFunctionSpec,
    TrackableShape,
    TrackingFunction,
    TrackingFunctionContext,
    TrackingFunctionShapeContext,
    TrackingFunctionSpec,
    attribute_spec,
    checkbox_attribute_spec,
    keypoint,
    keypoint_spec,
    label_spec,
    mask,
    number_attribute_spec,
    polygon,
    radio_attribute_spec,
    rectangle,
    select_attribute_spec,
    shape,
    skeleton,
    skeleton_label_spec,
    tag,
    text_attribute_spec,
)

__all__ = [
    "AutoAnnotationFunction",
    "BadFunctionError",
    "DetectionAnnotation",
    "DetectionFunction",
    "DetectionFunctionContext",
    "DetectionFunctionSpec",
    "TrackableShape",
    "TrackingFunction",
    "TrackingFunctionContext",
    "TrackingFunctionShapeContext",
    "TrackingFunctionSpec",
    "annotate_task",
    "attribute_spec",
    "checkbox_attribute_spec",
    "keypoint",
    "keypoint_spec",
    "label_spec",
    "mask",
    "number_attribute_spec",
    "polygon",
    "radio_attribute_spec",
    "rectangle",
    "select_attribute_spec",
    "shape",
    "skeleton",
    "skeleton_label_spec",
    "tag",
    "text_attribute_spec",
]
