import React from 'react';

import SVGCVATLogo from './assets/cvat-logo.svg';
import SVGAccountIcon from './assets/account-icon.svg';
import SVGEmptyTasksIcon from './assets/empty-tasks-icon.svg';
import SVGMenuIcon from './assets/menu-icon.svg';
import SVGCursorIcon from './assets/cursor-icon.svg';
import SVGMoveIcon from './assets/move-icon.svg';
import SVGRotateIcon from './assets/rotate-icon.svg';
import SVGFitIcon from './assets/fit-to-window-icon.svg';
import SVGZoomIcon from './assets/zoom-icon.svg';
import SVGRectangleIcon from './assets/rectangle-icon.svg';
import SVGPolygonIcon from './assets/polygon-icon.svg';
import SVGPointIcon from './assets/point-icon.svg';
import SVGPolylineIcon from './assets/polyline-icon.svg';
import SVGTagIcon from './assets/tag-icon.svg';
import SVGMergeIcon from './assets/merge-icon.svg';
import SVGGroupIcon from './assets/group-icon.svg';
import SVGSplitIcon from './assets/split-icon.svg';
import SVGMainMenuIcon from './assets/main-menu-icon.svg';
import SVGSaveIcon from './assets/save-icon.svg';
import SVGUndoIcon from './assets/undo-icon.svg';
import SVGRedoIcon from './assets/redo-icon.svg';
import SVGPlaycontrolFirstIcon from './assets/playcontrol-first-icon.svg';
import SVGPlaycontrolBackJumpIcon from './assets/playcontrol-back-jump-icon.svg';
import SVGPlaycontrolPreviousIcon from './assets/playcontrol-previous-icon.svg';
import SVGPlaycontrolPlayIcon from './assets/playcontrol-play-icon.svg';
import SVGPlaycontrolNextIcon from './assets/playcontrol-next-icon.svg';
import SVGPlaycontrolForwardJumpIcon from './assets/playcontrol-forward-jump-icon.svg';
import SVGPlaycontrolLastIcon from './assets/playcontrol-last-icon.svg';
import SVGInfoIcon from './assets/info-icon.svg';
import SVGFullscreenIcon from './assets/fullscreen-icon.svg';


export const CVATLogo = (): JSX.Element => <SVGCVATLogo />;
export const AccountIcon = (): JSX.Element => <SVGAccountIcon />;
export const EmptyTasksIcon = (): JSX.Element => <SVGEmptyTasksIcon />;
export const MenuIcon = (): JSX.Element => <SVGMenuIcon />;
export const CursorIcon = (): JSX.Element => <SVGCursorIcon />;
export const MoveIcon = (): JSX.Element => <SVGMoveIcon />;
export const RotateIcon = (): JSX.Element => <SVGRotateIcon />;
export const FitIcon = (): JSX.Element => <SVGFitIcon />;
export const ZoomIcon = (): JSX.Element => <SVGZoomIcon />;
export const RectangleIcon = (): JSX.Element => <SVGRectangleIcon />;
export const PolygonIcon = (): JSX.Element => <SVGPolygonIcon />;
export const PointIcon = (): JSX.Element => <SVGPointIcon />;
export const PolylineIcon = (): JSX.Element => <SVGPolylineIcon />;
export const TagIcon = (): JSX.Element => <SVGTagIcon />;
export const MergeIcon = (): JSX.Element => <SVGMergeIcon />;
export const GroupIcon = (): JSX.Element => <SVGGroupIcon />;
export const SplitIcon = (): JSX.Element => <SVGSplitIcon />;
export const MainMenuIcon = (): JSX.Element => <SVGMainMenuIcon />;
export const SaveIcon = (): JSX.Element => <SVGSaveIcon />;
export const UndoIcon = (): JSX.Element => <SVGUndoIcon />;
export const RedoIcon = (): JSX.Element => <SVGRedoIcon />;
export const PlaycontrolFirstIcon = (): JSX.Element => <SVGPlaycontrolFirstIcon />;
export const PlaycontrolBackJumpIcon = (): JSX.Element => <SVGPlaycontrolBackJumpIcon />;
export const PlaycontrolPreviousIcon = (): JSX.Element => <SVGPlaycontrolPreviousIcon />;
export const PlaycontrolPlayIcon = (): JSX.Element => <SVGPlaycontrolPlayIcon />;
export const PlaycontrolNextIcon = (): JSX.Element => <SVGPlaycontrolNextIcon />;
export const PlaycontrolForwardJumpIcon = (): JSX.Element => <SVGPlaycontrolForwardJumpIcon />;
export const PlaycontrolLastIcon = (): JSX.Element => <SVGPlaycontrolLastIcon />;
export const InfoIcon = (): JSX.Element => <SVGInfoIcon />;
export const FullscreenIcon = (): JSX.Element => <SVGFullscreenIcon />;
