# Generated by Django 4.2.1 on 2023-06-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("engine", "0070_add_job_type_created_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="analytics_report",
                        serialize=False,
                        to="engine.job",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("statistics", models.JSONField()),
            ],
        ),
    ]
