# Generated by Django 4.2.1 on 2023-07-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0072_alter_issue_updated_date"),
        ("analytics_report", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsreport",
            name="job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_report",
                to="engine.job",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="project",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_report",
                to="engine.project",
            ),
        ),
        migrations.AlterField(
            model_name="analyticsreport",
            name="task",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_report",
                to="engine.task",
            ),
        ),
    ]
