# Generated by Django 4.2.1 on 2023-06-26 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics_report", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analyticsreport",
            old_name="date",
            new_name="created_date",
        ),
    ]
