{{- if .Values.postgresql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl .Values.postgresql.secret.name . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
type: generic
stringData:
  {{- if and .Values.postgresql.customUser .Values.postgresql.customUser.name .Values.postgresql.customUser.database }}
  database: {{ .Values.postgresql.customUser.database | quote }}
  username: {{ .Values.postgresql.customUser.name | quote }}
  {{- else if and .Values.postgresql.auth .Values.postgresql.auth.username .Values.postgresql.auth.database }}
  database: {{ .Values.postgresql.auth.database | quote }}
  username: {{ .Values.postgresql.auth.username | quote }}
  {{- else }}
  {{- fail ".Values.postgresql.customUser or .Values.postgresql.auth must define username and database" }}
  {{- end }}
  password: {{ .Values.postgresql.secret.password | quote }}
  postgres-password: {{ .Values.postgresql.secret.postgres_password | quote }}
  replication-password: {{ .Values.postgresql.secret.replication_password | quote }}
{{- end }}
