# Generated by Django 2.1.9 on 2019-07-04 07:19

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import os

def create_builtins(apps, schema_editor):
    AnnoDumperModel = apps.get_model('annotation', 'AnnoDumper')
    AnnoParserModel = apps.get_model('annotation', 'AnnoParser')

    path_prefix = ""
    if "development" == os.environ.get("DJANGO_CONFIGURATION", "development"):
        path_prefix = os.path.join("..", "cvat", "apps", "annotation")

    AnnoDumperModel(
        name="cvat_annotation",
        file_extension="xml",
        handler_file=os.path.join(path_prefix, "builtin", "cvat", "dumper.py"),
        owner=None,
    ).save()

    AnnoDumperModel(
        name="cvat_interpolation",
        file_extension="xml",
        handler_file=os.path.join(path_prefix, "builtin", "cvat", "dumper.py"),
        owner=None,
    ).save()

    AnnoParserModel(
        name="cvat",
        handler_file=os.path.join(path_prefix, "builtin", "cvat", "parser.py"),
        owner=None,
    ).save()

    AnnoDumperModel(
        name="pascal_voc",
        file_extension="zip",
        handler_file=os.path.join(path_prefix, "builtin", "pascal_voc", "dumper.py"),
        owner=None,
    ).save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoDumper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cvat.apps.engine.models.SafeCharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('file_extension', models.CharField(max_length=32)),
                ('handler_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=settings.ANNO_FORMATS_ROOT), upload_to=cvat.apps.annotation.models.upload_dumper_handler)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnoParser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', cvat.apps.engine.models.SafeCharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('file_extension', models.CharField(max_length=32)),
                ('handler_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=settings.ANNO_FORMATS_ROOT), upload_to=cvat.apps.annotation.models.upload_parser_handler)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_builtins),
        migrations.AlterModelOptions(
            name='annodumper',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='annoparser',
            options={'default_permissions': ()},
        ),
        migrations.AlterField(
            model_name='annodumper',
            name='name',
            field=cvat.apps.engine.models.SafeCharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='annoparser',
            name='name',
            field=cvat.apps.engine.models.SafeCharField(max_length=256),
        ),
    ]
