# Generated by Django 4.2.1 on 2023-07-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0072_alter_issue_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributespec",
            name="default_value",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="attributespec",
            name="values",
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
