# Generated by Django 4.2.1 on 2023-07-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0073_alter_attributespec_default_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labeledimage",
            name="source",
            field=models.CharField(
                choices=[
                    ("auto", "AUTO"),
                    ("semi-auto", "SEMI_AUTO"),
                    ("manual", "MANUAL"),
                    ("file", "FILE"),
                ],
                default="manual",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="labeledshape",
            name="source",
            field=models.CharField(
                choices=[
                    ("auto", "AUTO"),
                    ("semi-auto", "SEMI_AUTO"),
                    ("manual", "MANUAL"),
                    ("file", "FILE"),
                ],
                default="manual",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="labeledtrack",
            name="source",
            field=models.CharField(
                choices=[
                    ("auto", "AUTO"),
                    ("semi-auto", "SEMI_AUTO"),
                    ("manual", "MANUAL"),
                    ("file", "FILE"),
                ],
                default="manual",
                max_length=16,
                null=True,
            ),
        ),
    ]
