# Generated by Django 4.2.13 on 2024-07-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0080_alter_trackedshape_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assignee_updated_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="assignee_updated_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="assignee_updated_date",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
