{{- if .Values.testing.minio.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: allow-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
data:
  allow_minio.sh: |
    # Allow CVAT requests to the in-cluster test MinIO via smokescreen.
    minio_ip_addr="$(getent hosts minio | head -1 | awk '{ print $1 }')"
    if [ -n "${minio_ip_addr}" ]; then
      export SMOKESCREEN_OPTS="$SMOKESCREEN_OPTS --allow-address=\"${minio_ip_addr}\""
    fi
{{- end }}
