{{- if .Values.testing.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKey: {{ .Values.testing.minio.accessKey | toString | toYaml }}
  secretKey: {{ .Values.testing.minio.secretKey | toString | toYaml }}
{{- end }}
