# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

import textwrap

from drf_spectacular.authentication import TokenScheme


class AccessTokenAuthenticationScheme(TokenScheme):
    """
    Adds the token auth method to schema. The description includes extra info
    comparing to what is generated by default.
    """

    target_class = "cvat.apps.access_tokens.authentication.AccessTokenAuthentication"
    name = "accessTokenAuth"
    priority = 0
    match_subclasses = True

    def get_security_definition(self, auto_schema):
        schema = super().get_security_definition(auto_schema)
        schema["description"] = textwrap.dedent(
            f"""\
            To authenticate using an API Access token, you need to include
            the 'Authentication' header with the '{self.target.keyword} ' prefix

            An API Access token has to be issued in the user profile section of the UI or
            via the /auth/access_tokens API before this authentication method can be used.
        """
        )
        return schema
