# Generated by Django 3.2.15 on 2022-11-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificationRetailer',
        ),
    ]
