# Generated by Django 3.2.15 on 2023-02-24 10:52
import logging

from django.db import migrations
from django.conf import settings


logger = logging.getLogger(__name__)


def move_retailer_import(apps, schema_migration):
    Project = apps.get_model('engine', 'Project')
    Task = apps.get_model('engine', 'Task')
    Organization = apps.get_model('organizations', 'Organization')

    projects = Project.objects.filter(name='Retailer import')
    orgs = Organization.objects.filter(name=settings.IMPORT_WORKSPACE)

    if projects and orgs:
        project = projects[0]
        organization = orgs[0]

        project.organization = organization
        project.save()

        tasks = Task.objects.filter(project=project)
        tasks.update(organization=organization)

    else:
        logger.warning('Either project or workspace not found. Migration not performed.')


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0002_delete_classificationretailer'),
    ]

    operations = [
        migrations.RunPython(move_retailer_import, migrations.RunPython.noop)
    ]
