# Generated by Django 3.2.15 on 2023-02-24 10:52
import logging

from django.db import migrations
from django.conf import settings


logger = logging.getLogger(__name__)


def move_retailer_import(apps, schema_migration):
    Project = apps.get_model('engine', 'Project')
    Organization = apps.get_model('organizations', 'Organization')

    try:
        project = Project.objects.get(name='Retailer import')
        organization = Organization.objects.get(slug=settings.IMPORT_WORKSPACE)

        project.organization = organization
        project.name = f'Import from {project.owner.username}'
        project.save()

        project.tasks.all().update(organization=organization)
    except Project.DoesNotExist:
        logger.warning('Project "Retailer import" does not exist. Skipping migration.')
    except Organization.DoesNotExist:
        logger.warning(f'Organization "{settings.IMPORT_WORKSPACE}" does not exist. Skipping migration.')


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0002_delete_classificationretailer'),
    ]

    operations = [
        migrations.RunPython(move_retailer_import, migrations.RunPython.noop)
    ]
