# Generated by Django 3.2.15 on 2023-08-21 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0067_task_priority'),
        ('rebotics', '0004_auto_20230227_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(choices=[('r3dev', 'r3dev'), ('r3us', 'r3us'), ('r3cn', 'r3cn'), ('local', 'local')], max_length=5)),
                ('gi_id', models.IntegerField()),
                ('url', models.CharField(max_length=2500)),
                ('name', models.CharField(default=None, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='FAILED', max_length=7)),
                ('frame', models.IntegerField(default=None, null=True)),
                ('task', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='engine.task')),
            ],
        ),
    ]
