# Generated by Django 3.2.15 on 2023-08-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0005_galleryimportprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimportprogress',
            name='url',
            field=models.CharField(max_length=3000),
        ),
    ]
