# Generated by Django 3.2.15 on 2023-09-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebotics', '0007_remove_galleryimportprogress_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimportprogress',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIP', 'Skip')], default='FAILED', max_length=7),
        ),
    ]
