# Generated by Django 4.2.1 on 2023-09-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="sent_date",
            field=models.DateTimeField(null=True),
        ),
    ]
