# Generated by Django 3.1.13 on 2021-09-20 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(null=True)),
                ('role', models.CharField(choices=[('W', 'Worker'), ('S', 'Supervisor'), ('M', 'Maintainer')], max_length=1)),
            ],
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AddField(
            model_name='organization',
            name='company',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.SlugField(max_length=256, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizations.membership'),
        ),
    ]
