# Generated by Django 3.2.7 on 2021-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('W', 'Worker'), ('S', 'Supervisor'), ('M', 'Maintainer'), ('O', 'Owner')], max_length=1),
        ),
    ]
