# Generated by Django 3.2.8 on 2021-10-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_membership_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='accepted',
        ),
    ]
