# Generated by Django 4.2.26 on 2025-11-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0002_invitation_sent_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("engine", "0096_add_model_registry"),
    ]

    operations = [
        migrations.CreateModel(
            name="AugmentationConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for the configuration",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description",
                    ),
                ),
                (
                    "pipeline",
                    models.JSONField(
                        help_text="Albumentations pipeline configuration as JSON"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this config was used",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this config was last used",
                        null=True,
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="If True, available as a template for all users in organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="augmentation_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this configuration belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="augmentation_configs",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_date"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AugmentationJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="User-friendly job name",
                        max_length=256,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description",
                    ),
                ),
                (
                    "config_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of the config at job creation time",
                    ),
                ),
                (
                    "dataset_name",
                    models.CharField(
                        help_text="Name for the augmented dataset (Drive folder)",
                        max_length=256,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version identifier (e.g., 'v1', 'v2', 'exp-20231122')",
                        max_length=64,
                    ),
                ),
                (
                    "augmentations_per_image",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of augmented copies to generate per image",
                    ),
                ),
                (
                    "drive_folder_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Google Drive folder ID where dataset is stored",
                        max_length=256,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("processing", "PROCESSING"),
                            ("completed", "COMPLETED"),
                            ("failed", "FAILED"),
                            ("cancelled", "CANCELLED"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current job status",
                        max_length=32,
                    ),
                ),
                (
                    "progress",
                    models.FloatField(
                        default=0.0,
                        help_text="Progress percentage (0-100)",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job started processing",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job completed",
                        null=True,
                    ),
                ),
                (
                    "total_images",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of source images",
                    ),
                ),
                (
                    "processed_images",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of source images processed",
                    ),
                ),
                (
                    "generated_images",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of augmented images generated",
                    ),
                ),
                (
                    "failed_images",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of images that failed to augment",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if job failed",
                    ),
                ),
                (
                    "rq_job_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Redis Queue job ID",
                        max_length=64,
                    ),
                ),
                (
                    "cloud_storage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Google Drive cloud storage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="augmentation_jobs",
                        to="engine.cloudstorage",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Augmentation pipeline configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="augmentation_manager.augmentationconfig",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created the job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="augmentation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this job belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="augmentation_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        help_text="Source task to augment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="augmentation_jobs",
                        to="engine.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_date"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AugmentationLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "log_level",
                    models.CharField(
                        choices=[
                            ("debug", "DEBUG"),
                            ("info", "INFO"),
                            ("warning", "WARNING"),
                            ("error", "ERROR"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=32,
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Log message"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., image_id, error_details)",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Augmentation job this log belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="augmentation_manager.augmentationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "default_permissions": (),
            },
        ),
        # Add indexes for AugmentationConfig
        migrations.AddIndex(
            model_name="augmentationconfig",
            index=models.Index(
                fields=["owner", "-created_date"],
                name="augmentatio_owner_i_1a2b3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="augmentationconfig",
            index=models.Index(
                fields=["organization", "is_template"],
                name="augmentatio_organiz_4d5e6f_idx",
            ),
        ),
        # Add indexes for AugmentationJob
        migrations.AddIndex(
            model_name="augmentationjob",
            index=models.Index(
                fields=["owner", "-created_date"],
                name="augmentatio_owner_i_7g8h9i_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="augmentationjob",
            index=models.Index(
                fields=["organization", "-created_date"],
                name="augmentatio_organiz_0j1k2l_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="augmentationjob",
            index=models.Index(
                fields=["task", "-created_date"],
                name="augmentatio_task_id_3m4n5o_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="augmentationjob",
            index=models.Index(
                fields=["status"],
                name="augmentatio_status_6p7q8r_idx",
            ),
        ),
        # Add indexes for AugmentationLog
        migrations.AddIndex(
            model_name="augmentationlog",
            index=models.Index(
                fields=["job", "-timestamp"],
                name="augmentatio_job_id_9s0t1u_idx",
            ),
        ),
    ]
