# Generated by Django 2.1.3 on 2019-01-23 10:05

import cvat.apps.git_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_manager', '0001_initial'),
    ]

    replaces = [('git', '0002_auto_20190123_1305')]

    operations = [
        migrations.AlterField(
            model_name='gitdata',
            name='status',
            field=models.CharField(default=cvat.apps.git_manager.models.GitStatusChoice('!sync'), max_length=20),
        ),
    ]
