# Generated by Django 2.0.9 on 2018-10-25 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0012_auto_20181025_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitData',
            fields=[
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='engine.Task')),
                ('url', models.URLField(max_length=2000)),
            ],
        ),
    ]
