# Generated by Django 3.2.14 on 2022-07-29 14:57

import cvat.apps.webhooks.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("engine", "0056_jobs_previews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("events", models.CharField(default="", max_length=4096)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Organization", "ORGANIZATION"),
                            ("Project", "PROJECT"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("application/json", "JSON")],
                        default=cvat.apps.webhooks.models.WebhookContentTypeChoice[
                            "JSON"
                        ],
                        max_length=64,
                    ),
                ),
                ("secret", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("enable_ssl", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="engine.project",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {
                    ("url", "secret", "enable_ssl", "type", "content_type")
                },
            },
        )
    ]
