# Generated by Django 3.2.15 on 2022-08-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdelivery',
            name='status_code',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='webhook',
            unique_together={('target_url', 'secret', 'enable_ssl', 'type', 'content_type', 'events')},
        ),
    ]
