# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

# Generated by Django 5.2.14 on 2026-07-31 08:28

from django.conf import settings
from django.core.management.base import CommandError
from django.db import migrations, models

SERVER_WEBHOOKS_EXIST_ERROR = """\
Cannot roll back: found {count} webhook(s) with type="server".
Nothing was changed. Aborting the migration.

Please review the existing "server" webhooks and delete them before continuing.
"""


def abort_if_server_webhooks_exist(apps, schema_editor):
    Webhook = apps.get_model("webhooks", "Webhook")

    count = Webhook.objects.filter(type="server").count()
    if count:
        raise CommandError(SERVER_WEBHOOKS_EXIST_ERROR.format(count=count))


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
        ("organizations", "0002_invitation_sent_date"),
        ("webhooks", "0007_remove_retired_organization_delete_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="webhook",
            name="webhooks_project_or_organization",
        ),
        migrations.AlterField(
            model_name="webhook",
            name="type",
            field=models.CharField(
                choices=[
                    ("organization", "ORGANIZATION"),
                    ("project", "PROJECT"),
                    ("server", "SERVER"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="webhook",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("project_id__isnull", False),
                        ("type", "project"),
                    ),
                    models.Q(
                        ("organization_id__isnull", False),
                        ("project_id__isnull", True),
                        ("type", "organization"),
                    ),
                    models.Q(
                        ("organization_id__isnull", True),
                        ("project_id__isnull", True),
                        ("type", "server"),
                    ),
                    _connector="OR",
                ),
                name="webhooks_project_or_organization_or_server",
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=abort_if_server_webhooks_exist,
        ),
    ]
