# Copyright (C) CVAT.ai Corporation
#
# SPDX-License-Identifier: MIT

# Generated by Django 5.2.16 on 2026-08-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0008_alter_webhook_type_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webhookdelivery",
            name="changed_fields",
        ),
    ]
