# Generated by Django 4.2.15 on 2024-12-29 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0005_qualitysettings_match_empty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qualitysettings",
            old_name="match_empty_frames",
            new_name="empty_is_annotated",
        ),
    ]
