// Copyright (C) 2021-2022 Intel Corporation
//
// SPDX-License-Identifier: MIT

export enum ProviderType {
    AWS_S3_BUCKET = 'AWS_S3_BUCKET',
    AZURE_CONTAINER = 'AZURE_CONTAINER',
    GOOGLE_CLOUD_STORAGE = 'GOOGLE_CLOUD_STORAGE',
}

export enum CredentialsType {
    KEY_SECRET_KEY_PAIR = 'KEY_SECRET_KEY_PAIR',
    ACCOUNT_NAME_TOKEN_PAIR = 'ACCOUNT_NAME_TOKEN_PAIR',
    ANONYMOUS_ACCESS = 'ANONYMOUS_ACCESS',
    CONNECTION_STRING = 'CONNECTION_STRING',
    KEY_FILE_PATH = 'KEY_FILE_PATH',
}

export enum StorageStatuses {
    AVAILABLE = 'AVAILABLE',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
}

export enum ShortcutScope {
    ALL = 'ALL',
    ANNOTATION_PAGE = 'ANNOTATION_PAGE',
    ANNOTATION_PAGE_STANDARD_WORKSPACE = 'ANNOTATION_PAGE_STANDARD_WORKSPACE',
    ANNOTATION_PAGE_ATTRIBUTE_ANNOTATION_WORKSPACE = 'ANNOTATION_PAGE_ATTRIBUTE_ANNOTATION_WORKSPACE',
    ANNOTATION_PAGE_CANVAS_WORKSPACE = 'ANNOTATION_PAGE_CANVAS_WORKSPACE',
    ANNOTATION_PAGE_REVIEW_WORKSPACE = 'ANNOTATION_PAGE_REVIEW_WORKSPACE',
    ANNOTATION_PAGE_SINGLE_SHAPE_WORKSPACE = 'ANNOTATION_PAGE_SINGLE_SHAPE_WORKSPACE',
    ANNOTATION_PAGE_TAG_ANNOATION_WORKSPACE = 'ANNOTATION_PAGE_TAG_ANNOATION_WORKSPACE',
    LABELS_EDITOR = 'LABELS_EDITOR',
    LAYOUT_GRID = 'LAYOUT_GRID',
}
