{{- if and .Values.traefik.enabled .Values.analytics.enabled }}

apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /analytics
{{- end }}
