# Generated by Django 4.2.13 on 2024-07-04 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0079_job_assignee_updated_date_and_more"),
        ("quality_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityreport",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quality_report",
                to="engine.job",
            ),
        ),
    ]
