# Generated by Django 4.2.1 on 2023-06-22 15:36

import django.db.models.deletion
from django.db import migrations, models


def copy_parents_to_new_field(apps, schema_editor):
    QualityReport = apps.get_model("quality_control", "QualityReport")

    reports = QualityReport.objects.all()
    QualityReportParentsRel = QualityReport.parents.through
    QualityReportParentsRel.objects.bulk_create(
        [
            QualityReportParentsRel(from_qualityreport=report, to_qualityreport=report.parent)
            for report in reports
            if report.parent
        ],
        batch_size=1000,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_reports",
                to="engine.project",
            ),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_settings",
                to="engine.project",
            ),
        ),
        migrations.AlterField(
            model_name="qualityreport",
            name="gt_last_updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="qualitysettings",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_settings",
                to="engine.task",
            ),
        ),
        migrations.AddField(
            model_name="qualityreport",
            name="parents",
            field=models.ManyToManyField(
                blank=True, to="quality_control.qualityreport", related_name="children"
            ),
        ),
        migrations.RunPython(
            code=copy_parents_to_new_field,
        ),
        migrations.RemoveField(
            model_name="qualityreport",
            name="parent",
        ),
    ]
