# Generated by Django 4.2.6 on 2024-06-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0002_annotationconflict_character_error_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationconflict",
            name="character_error_rate",
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="annotationconflict",
            name="word_error_rate",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
