# Generated by Django 4.2.15 on 2024-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0003_qualityreport_assignee_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="use_image_space_for_point_group_comparisons",
            field=models.BooleanField(default=False),
        ),
    ]
