# Generated by Django 4.2.15 on 2024-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0003_qualityreport_assignee_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="use_bbox_size_for_points",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
