# Generated by Django 4.2.6 on 2024-06-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0003_alter_annotationconflict_character_error_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="cer_threshold",
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="compare_extra_parameters",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="wer_threshold",
            field=models.FloatField(default=0.2),
        ),
    ]
