# Generated by Django 4.2.15 on 2024-11-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0004_qualitysettings_point_size_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="match_empty_frames",
            field=models.BooleanField(default=False),
        ),
    ]
