# Generated by Django 4.2.18 on 2025-02-17 18:01

import django.db.models.deletion
from django.db import migrations, models


def init_settings_in_existing_projects(apps, schema_editor):
    Project = apps.get_model("engine", "Project")
    QualitySettings = apps.get_model("quality", "QualitySettings")

    projects_without_settings = Project.objects.filter(quality_settings__isnull=True).distinct()
    QualitySettings.objects.bulk_create(
        [QualitySettings(project=p) for p in projects_without_settings],
        batch_size=10000,
    )

    # Preserve existing quality settings for tasks in projects
    (
        QualitySettings.objects.filter(task__project__isnull=False).update(
            {"inherit": False}, update_fields=["inherit"]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0088_consensus_jobs"),
        ("quality_control", "0006_rename_match_empty_frames_qualitysettings_empty_is_annotated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qualityreport",
            name="parent",
        ),
        migrations.AddField(
            model_name="qualityreport",
            name="parents",
            field=models.ManyToManyField(
                blank=True, related_name="children", to="quality_control.qualityreport"
            ),
        ),
        migrations.AddField(
            model_name="qualityreport",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_reports",
                to="engine.project",
            ),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="inherit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="qualitysettings",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_settings",
                to="engine.project",
            ),
        ),
        migrations.AlterField(
            model_name="qualityreport",
            name="gt_last_updated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="qualitysettings",
            name="task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_settings",
                to="engine.task",
            ),
        ),
        migrations.RunPython(
            init_settings_in_existing_projects,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
