# Generated by Django 4.2.18 on 2025-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0007_project_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="job_filter",
            field=models.TextField(
                blank=True, default='{"==": [{"var": "type"}, "annotation"]}', max_length=1024
            ),
        ),
    ]
