# Generated by Django 4.2.18 on 2025-03-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0007_project_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="job_filter",
            field=models.JSONField(default=list),
        ),
    ]
