# Generated by Django 4.2.21 on 2025-11-21 16:21

from django.db import migrations


def init_settings_in_existing_tasks(apps, schema_editor):
    """
    Initialize default quality settings for tasks that do not have them.
    This is done at task creation for new tasks, but the old ones might need to be updated.
    For such tasks, settings would be created on the first quality report request,
    but opening the quality control page for them results in a page without the settings tab.
    """

    Task = apps.get_model("engine", "Task")
    QualitySettings = apps.get_model("quality_control", "QualitySettings")

    tasks_without_settings = Task.objects.filter(quality_settings__isnull=True).values_list(
        "id", flat=True
    )

    QualitySettings.objects.bulk_create(
        [
            QualitySettings(
                task_id=tid,
                inherit=True,
                compare_attributes=True,
                iou_threshold=0.4,
                oks_sigma=0.09,
                line_thickness=0.01,
                low_overlap_threshold=0.8,
                point_size_base="group_bbox_size",
                compare_line_orientation=True,
                line_orientation_threshold=0.1,
                compare_groups=True,
                group_match_threshold=0.5,
                check_covered_annotations=True,
                object_visibility_threshold=0.05,
                panoptic_comparison=True,
                empty_is_annotated=False,
                target_metric="accuracy",
                target_metric_threshold=0.7,
                max_validations_per_job=0,
            )
            for tid in tasks_without_settings
        ],
        batch_size=10000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0010_qualityreport_quality_report_job_or_task_or_project"),
    ]

    operations = [
        migrations.RunPython(
            init_settings_in_existing_tasks,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
