# Generated by Django 5.2.14 on 2026-05-25 17:34

import django.db.models.deletion
from django.db import migrations, models

import cvat.apps.quality_control.models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
        ("quality_control", "0011_default_quality_settings_for_old_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationconflict",
            name="attributes",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="annotationconflict",
            name="frame",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="annotationid",
            name="type",
            field=models.CharField(
                choices=[
                    ("tag", "TAG"),
                    ("shape", "SHAPE"),
                    ("track", "TRACK"),
                    ("interval", "INTERVAL"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TranscriptionQualityRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("wer", "WER"), ("cer", "CER")],
                        default=cvat.apps.quality_control.models.TranscriptionQualityMetric["WER"],
                        max_length=32,
                    ),
                ),
                ("acceptance_threshold", models.FloatField()),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.attributespec",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_requirements",
                        related_query_name="transcription_requirement",
                        to="quality_control.qualitysettings",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("acceptance_threshold__gte", 0), ("acceptance_threshold__lte", 1)
                        ),
                        name="transcription_quality_requirement_threshold_is_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("settings_id", "attribute_id"),
                        name="transcription_quality_requirement_attr_unique_per_settings",
                    ),
                ],
            },
        ),
    ]
