# Generated by Django 4.2.26 on 2026-04-08 16:42

import django.db.models.deletion
from django.db import migrations, models

import cvat.apps.quality_control.models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0101_labeledinterval_labeledintervalattributeval"),
        ("quality_control", "0011_default_quality_settings_for_old_tasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationconflict",
            name="attributes",
            field=models.JSONField(default=str),
        ),
        migrations.AlterField(
            model_name="annotationid",
            name="type",
            field=models.CharField(
                choices=[
                    ("tag", "TAG"),
                    ("shape", "SHAPE"),
                    ("track", "TRACK"),
                    ("interval", "INTERVAL"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TranscriptionQualityRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("wer", "WER"), ("cer", "CER")],
                        default=cvat.apps.quality_control.models.TranscriptionQualityMetric["WER"],
                        max_length=32,
                    ),
                ),
                ("acceptance_threshold", models.FloatField()),
                (
                    "attribute",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="engine.attributespec",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_requirements",
                        related_query_name="transcription_requirement",
                        to="quality_control.qualitysettings",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="transcriptionqualityrequirement",
            constraint=models.CheckConstraint(
                check=models.Q(("acceptance_threshold__gte", 0), ("acceptance_threshold__lte", 1)),
                name="transcription_quality_requirement_threshold_is_valid",
            ),
        ),
    ]
