# Generated by Django 4.2.26 on 2026-03-04 11:25

import cvat.apps.quality_control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0011_default_quality_settings_for_old_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "annotation_type",
                    models.CharField(
                        choices=[
                            ("tag", "Tag"),
                            ("rectangle", "Rectangle"),
                            ("skeleton", "Skeleton"),
                            ("skeleton_keypoint", "Skeleton Keypoint"),
                            ("points", "Points"),
                            ("polyline", "Polyline"),
                            ("mask", "Mask"),
                            ("polygon", "Polygon"),
                            ("ellipse", "Ellipse"),
                            ("attribute", "Attribute"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "target_metric",
                    models.CharField(
                        choices=[
                            ("accuracy", "ACCURACY"),
                            ("precision", "PRECISION"),
                            ("recall", "RECALL"),
                        ],
                        default=cvat.apps.quality_control.models.QualityTargetMetricType[
                            "ACCURACY"
                        ],
                        max_length=32,
                    ),
                ),
                ("target_metric_threshold", models.FloatField(default=0.7)),
                ("iou_threshold", models.FloatField()),
                ("oks_sigma", models.FloatField()),
                ("line_thickness", models.FloatField()),
                ("low_overlap_threshold", models.FloatField()),
                (
                    "point_size_base",
                    models.CharField(
                        choices=[
                            ("image_size", "IMAGE_SIZE"),
                            ("group_bbox_size", "GROUP_BBOX_SIZE"),
                        ],
                        default=cvat.apps.quality_control.models.PointSizeBase["GROUP_BBOX_SIZE"],
                        max_length=32,
                    ),
                ),
                ("compare_line_orientation", models.BooleanField()),
                ("line_orientation_threshold", models.FloatField()),
                ("compare_groups", models.BooleanField()),
                ("group_match_threshold", models.FloatField()),
                ("check_covered_annotations", models.BooleanField()),
                ("object_visibility_threshold", models.FloatField()),
                ("panoptic_comparison", models.BooleanField()),
                ("compare_attributes", models.BooleanField()),
                ("empty_is_annotated", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="qualitysettings",
            name="quality_settings_task_or_project",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="check_covered_annotations",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="compare_attributes",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="compare_groups",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="compare_line_orientation",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="empty_is_annotated",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="group_match_threshold",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="iou_threshold",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="line_orientation_threshold",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="line_thickness",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="low_overlap_threshold",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="object_visibility_threshold",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="oks_sigma",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="panoptic_comparison",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="point_size_base",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="target_metric",
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="target_metric_threshold",
        ),
        migrations.AddConstraint(
            model_name="qualitysettings",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("task_id__isnull", False), ("project_id__isnull", False), _connector="XOR"
                ),
                name="quality_settings_task_or_project",
            ),
        ),
        migrations.AddField(
            model_name="qualityrequirement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="quality_control.qualityrequirement",
            ),
        ),
        migrations.AddField(
            model_name="qualityrequirement",
            name="settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                related_query_name="requirement",
                to="quality_control.qualitysettings",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityrequirement",
            constraint=models.UniqueConstraint(
                fields=("settings", "name"), name="quality_requirements_unique_per_settings"
            ),
        ),
    ]
