# Generated by Django 4.2.26 on 2026-04-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0012_annotationconflict_attributes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationconflict",
            name="attributes",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="annotationconflict",
            name="frame",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
