# Generated by Django 5.2.14 on 2026-09-28 09:49

from django.db import migrations, models
from django.utils import timezone

_BASE_REQUIREMENT_DEFAULTS = {
    "target_metric": "accuracy",
    "target_metric_threshold": 0.7,
    "iou_threshold": 0.4,
    "oks_sigma": 0.09,
    "line_thickness": 0.01,
    "point_size_base": "group_bbox_size",
    "compare_line_orientation": True,
    "line_orientation_threshold": 0.1,
    "compare_groups": True,
    "group_match_threshold": 0.5,
    "check_covered_annotations": True,
    "object_visibility_threshold": 0.05,
    "panoptic_comparison": True,
    "compare_attributes": False,
    "attribute_comparison": None,
}


def add_interval_requirements(apps, schema_editor):
    Settings = apps.get_model("quality_control", "QualitySettings")
    Requirement = apps.get_model("quality_control", "QualityRequirement")
    alias = schema_editor.connection.alias
    requirements = Requirement.objects.using(alias)
    for settings_id in (
        Settings.objects.using(alias).values_list("id", flat=True).iterator(chunk_size=500)
    ):
        existing = requirements.filter(settings_id=settings_id)
        if existing.filter(parent_id=None, annotation_type="interval").exists():
            continue
        if (
            conflicting_id := existing.filter(name="Base interval")
            .values_list("id", flat=True)
            .first()
        ):
            names = set(existing.values_list("name", flat=True))
            name = "Base interval (custom)"
            suffix = 2
            while name in names:
                name = f"Base interval (custom) {suffix}"
                suffix += 1
            existing.filter(id=conflicting_id).update(name=name, updated_date=timezone.now())
        requirements.create(
            settings_id=settings_id,
            name="Base interval",
            sort_order=9,
            annotation_type="interval",
            enabled=False,
            filter="",
            **_BASE_REQUIREMENT_DEFAULTS,
        )
        Settings.objects.using(alias).filter(id=settings_id).update(updated_date=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0013_alter_qualityrequirement_target_metric"),
    ]

    operations = [
        migrations.RunPython(add_interval_requirements, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="annotationconflict",
            name="frame",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="annotationid",
            name="type",
            field=models.CharField(
                choices=[
                    ("tag", "TAG"),
                    ("shape", "SHAPE"),
                    ("track", "TRACK"),
                    ("interval", "INTERVAL"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="annotation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tag", "Tag"),
                    ("rectangle", "Rectangle"),
                    ("skeleton", "Skeleton"),
                    ("skeleton_keypoint", "Skeleton Keypoint"),
                    ("points", "Points"),
                    ("polyline", "Polyline"),
                    ("mask", "Mask"),
                    ("polygon", "Polygon"),
                    ("ellipse", "Ellipse"),
                    ("interval", "Interval"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
