# Generated by Django 4.2.26 on 2026-04-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0013_alter_annotationconflict_attributes_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="transcriptionqualityrequirement",
            constraint=models.UniqueConstraint(
                fields=("settings_id", "attribute_id"),
                name="transcription_quality_requirement_attr_unique_per_settings",
            ),
        ),
    ]
