# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models

import cvat.apps.quality_control.models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0014_annotationconflict_attribute_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityrequirement",
            name="attribute_comparison",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="qualityrequirement",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="annotation_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tag", "Tag"),
                    ("rectangle", "Rectangle"),
                    ("skeleton", "Skeleton"),
                    ("skeleton_keypoint", "Skeleton Keypoint"),
                    ("points", "Points"),
                    ("polyline", "Polyline"),
                    ("mask", "Mask"),
                    ("polygon", "Polygon"),
                    ("ellipse", "Ellipse"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="check_covered_annotations",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="compare_attributes",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="compare_groups",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="compare_line_orientation",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="empty_is_annotated",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="group_match_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="iou_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="line_orientation_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="line_thickness",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="low_overlap_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="object_visibility_threshold",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="oks_sigma",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="panoptic_comparison",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="quality_control.qualityrequirement",
            ),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="point_size_base",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image_size", "IMAGE_SIZE"),
                    ("group_bbox_size", "GROUP_BBOX_SIZE"),
                ],
                default=cvat.apps.quality_control.models.PointSizeBase["GROUP_BBOX_SIZE"],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="target_metric",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accuracy", "ACCURACY"),
                    ("precision", "PRECISION"),
                    ("recall", "RECALL"),
                ],
                default=cvat.apps.quality_control.models.QualityTargetMetricType["ACCURACY"],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="qualityrequirement",
            name="target_metric_threshold",
            field=models.FloatField(blank=True, default=0.7, null=True),
        ),
    ]
