# Generated by Django 5.2.14 on 2026-05-27 18:42

from django.db import migrations, models


def interval_boundary_tolerance_forward(apps, schema_editor):
    QualitySettings = apps.get_model("quality_control", "QualitySettings")
    QualitySettings.objects.update(
        interval_boundary_tolerance=models.F("interval_boundary_tolerance_s") * 1000
    )


def interval_boundary_tolerance_backward(apps, schema_editor):
    QualitySettings = apps.get_model("quality_control", "QualitySettings")
    QualitySettings.objects.update(
        interval_boundary_tolerance_s=models.F("interval_boundary_tolerance") / 1000
    )


class Migration(migrations.Migration):

    dependencies = [
        ("quality_control", "0014_qualitysettings_target_metric_transcription"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitysettings",
            name="interval_boundary_tolerance",
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.RunPython(
            interval_boundary_tolerance_forward, interval_boundary_tolerance_backward
        ),
        migrations.RemoveField(
            model_name="qualitysettings",
            name="interval_boundary_tolerance_s",
        ),
    ]
