# Generated by Codex on 2026-05-21

from django.db import migrations, models


_DEFAULT_REQUIREMENT_ANNOTATION_TYPES = (
    "tag",
    "rectangle",
    "skeleton",
    "skeleton_keypoint",
    "points",
    "polyline",
    "mask",
    "polygon",
    "ellipse",
)

_ROOT_REQUIREMENT_DEFAULTS = {
    "target_metric": "accuracy",
    "target_metric_threshold": 0.7,
    "iou_threshold": 0.4,
    "oks_sigma": 0.09,
    "line_thickness": 0.01,
    "low_overlap_threshold": 0.8,
    "point_size_base": "group_bbox_size",
    "compare_line_orientation": True,
    "line_orientation_threshold": 0.1,
    "compare_groups": True,
    "group_match_threshold": 0.5,
    "check_covered_annotations": True,
    "object_visibility_threshold": 0.05,
    "panoptic_comparison": True,
    "compare_attributes": True,
    "attribute_comparison": None,
    "empty_is_annotated": False,
}


def _default_requirement_name(annotation_type: str) -> str:
    return f"default:{annotation_type}"


def _ensure_default_quality_requirements(apps, _schema_editor):
    QualitySettings = apps.get_model("quality_control", "QualitySettings")
    QualityRequirement = apps.get_model("quality_control", "QualityRequirement")

    default_names = {
        _default_requirement_name(annotation_type)
        for annotation_type in _DEFAULT_REQUIREMENT_ANNOTATION_TYPES
    }

    for settings_id in QualitySettings.objects.values_list("id", flat=True).iterator():
        existing_default_names = set(
            QualityRequirement.objects.filter(
                settings_id=settings_id,
                name__in=default_names,
            ).values_list("name", flat=True)
        )

        if existing_default_names:
            QualityRequirement.objects.filter(
                settings_id=settings_id,
                name__in=existing_default_names,
            ).update(is_default=True)

        requirements_to_create = []
        for sort_order, annotation_type in enumerate(_DEFAULT_REQUIREMENT_ANNOTATION_TYPES):
            name = _default_requirement_name(annotation_type)
            if name in existing_default_names:
                continue

            requirements_to_create.append(
                QualityRequirement(
                    settings_id=settings_id,
                    name=name,
                    is_default=True,
                    sort_order=sort_order,
                    filter="",
                    enabled=False,
                    annotation_type=annotation_type,
                    parent_id=None,
                    **_ROOT_REQUIREMENT_DEFAULTS,
                )
            )

        QualityRequirement.objects.bulk_create(requirements_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0015_hierarchical_quality_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityrequirement",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveConstraint(
            model_name="qualitysettings",
            name="quality_settings_task_or_project",
        ),
        migrations.AddConstraint(
            model_name="qualitysettings",
            constraint=models.CheckConstraint(
                name="quality_settings_task_or_project",
                condition=(
                    models.Q(task_id__isnull=False, project_id__isnull=True)
                    | models.Q(task_id__isnull=True, project_id__isnull=False)
                ),
            ),
        ),
        migrations.RunPython(
            _ensure_default_quality_requirements,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
