# Generated by Codex on 2026-06-10

from django.db import migrations

_DEFAULT_REQUIREMENT_ANNOTATION_TYPES = (
    "tag",
    "rectangle",
    "skeleton",
    "skeleton_keypoint",
    "points",
    "polyline",
    "mask",
    "polygon",
    "ellipse",
)


def _default_requirement_name(annotation_type: str) -> str:
    return f"Default {annotation_type.replace('_', ' ')}"


def _legacy_default_requirement_name(annotation_type: str) -> str:
    return f"default:{annotation_type}"


def _rename_default_quality_requirements(apps, _schema_editor):
    QualityRequirement = apps.get_model("quality_control", "QualityRequirement")

    for annotation_type in _DEFAULT_REQUIREMENT_ANNOTATION_TYPES:
        QualityRequirement.objects.filter(
            name=_legacy_default_requirement_name(annotation_type),
            annotation_type=annotation_type,
        ).update(name=_default_requirement_name(annotation_type), is_default=True)


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0017_remove_quality_warning_results"),
    ]

    operations = [
        migrations.RunPython(
            _rename_default_quality_requirements,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
