(
    ["server:includes"]="smokescreen clamav"

    ["worker:annotation"]="smokescreen"
    ["worker:chunks"]="smokescreen"
    ["worker:consensus"]=""
    ["worker:export"]="smokescreen"
    ["worker:import"]="smokescreen clamav"
    ["worker:quality_reports"]=""
    ["worker:cleaning"]="rqscheduler"
    ["worker:webhooks"]="smokescreen"
    ["worker:notifications"]=""
)
