name: Build image

# Note:
# HARBOR_URL, HARBOR_USERNAME, HARBOR_TOKEN are defined at the organization level

on:
  push:
    branches:
      - 'v2.7.3-AI4OS'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:       
    
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_URL  }}
          username: ${{ vars.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push (server)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/ai4-cvat-server:${{ github.ref_name }}
          file: ./Dockerfile

      - name: Build and push (ui)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/ai4-cvat-ui:${{ github.ref_name }}
          file: ./Dockerfile.ui
