name: Cache
on:
  push:
    branches:
      - 'develop'

jobs:
  Caching_CVAT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub for BuildKit cache
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Caching CVAT Server
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_WORKSPACE }}/server:buildcache-develop
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_WORKSPACE }}/server:buildcache-develop,mode=max,image-manifest=true,oci-mediatypes=true

      - name: Caching CVAT UI
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.ui
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_WORKSPACE }}/ui:buildcache-develop
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKERHUB_WORKSPACE }}/ui:buildcache-develop,mode=max,image-manifest=true,oci-mediatypes=true
