name: get_secret_values
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up secret file
      env:
        DEBUG_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DEBUG_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        echo $DEBUG_USERNAME >> secrets.txt
        echo $DEBUG_PASSWORD >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
