name: docker_public_test
on: pull_request
jobs:
  helm:
    runs-on: ubuntu-latest
#    continue-on-error: true
#    needs: main
    steps:
      - uses: actions/checkout@v4
#        with:
#          ref: "release-${{ needs.main.outputs.version }}"  #warn not needed for testing
      # v4.3.1
      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4
        with:
          version: v3.14.4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up secret file
        env:
          DEBUG_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DEBUG_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $DEBUG_USER >> secrets.txt
          echo $DEBUG_PASSWORD >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v3

      - name: Package Helm chart
        working-directory: helm-chart
        run: |
          helm dependency update && helm package . --version "v2.44.1" && mv cvat-*.tgz ../
          echo "CHART_FILE=$(ls ../cvat-*.tgz | xargs basename)" >> $GITHUB_ENV
#todo change hardcoded --version to ${{ needs.main.outputs.version }}
      - name: Push Helm chart to Docker Hub
        run: |
          helm push ${{ env.CHART_FILE }} oci://registry-1.docker.io/cvat/helm-charts
