name: get_secret_values

on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up secret file
        env:
          DEBUG_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DEBUG_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DEBUG_WORKSPACE: ${{ secrets.DOCKERHUB_WORKSPACE }}
        run: |
          echo $DEBUG_USERNAME >> secrets.txt
          echo $DEBUG_TOKEN >> secrets.txt
          echo $DEBUG_WORKSPACE >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
