name: isort
on: pull_request
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run checks
        run: |
          pipx install $(grep "^isort" ./dev/requirements.txt)

          echo "isort version: $(isort --version-number)"

          isort --check --diff --resolve-all-configs .
