name: Setup Yarn
description: Set up Node.js, enable Yarn via Corepack, cache dependencies, and install packages

inputs:
  node-version:
    description: Node.js version to install
    required: false
    default: 22.x
  node-modules-path:
    description: Paths to cache for node_modules
    required: false
    default: node_modules
  install-command:
    description: Command used to install dependencies
    required: false
    default: yarn install --immutable

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable corepack
      shell: bash
      run: corepack enable yarn

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    - name: Cache yarn cache
      uses: actions/cache@v4
      id: cache-yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Get yarn version
      id: yarn-version
      shell: bash
      run: echo "version=$(node --version)" >> $GITHUB_OUTPUT

    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: ${{ inputs.node-modules-path }}
        key: ${{ runner.os }}-${{ steps.yarn-version.outputs.version }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ steps.yarn-version.outputs.version }}-nodemodules-

    - name: Install dependencies
      if: |
        steps.cache-yarn-cache.outputs.cache-hit != 'true' ||
        steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.install-command }}
