# Generated by Django 2.1.9 on 2019-07-08 15:45

import cvat.apps.auto_annotation.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmodel',
            name='preprocessing_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=cvat.apps.auto_annotation.models.upload_path_handler),
        ),
    ]
