# Generated by Django 2.2.4 on 2019-12-19 02:33

import cvat.apps.auto_annotation.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationmodel',
            name='classes_file',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(), upload_to=cvat.apps.auto_annotation.models.upload_path_handler),
        ),
        migrations.AddField(
            model_name='annotationmodel',
            name='model_type',
            field=cvat.apps.auto_annotation.models.SafeCharField(default='openvino', max_length=256),
        ),
        migrations.AddField(
            model_name='annotationmodel',
            name='tf_model_file',
            field=models.FileField(default=None, storage=django.core.files.storage.FileSystemStorage(), upload_to=cvat.apps.auto_annotation.models.upload_path_handler),
        ),
    ]